// ---------------------------------------------------------------- catalog (generated by scripts/rate-catalog/build_v3.py)
export type Channel = "B2B" | "D2C" | "Both";
export type When = Record<string, string[]>;

export interface Cond { id: string; label: string; values: string[]; common: boolean; free: boolean; help: string }
export interface DriverValue { v: string; d: number | null }
export interface Driver { id: string; label: string; kind: "attr" | "volume"; values: DriverValue[]; when: When; calc: boolean; help: string }
export interface Unit {
  id: string; label: string; flat: number; lo: number; hi: number; basis: string; drivers: Driver[]; mins: string[];
  second: boolean; common: boolean; when: When; by: Record<string, Record<string, number>>;
  byCombo: { when: Record<string, string>; d: number }[]; minDefault: Record<string, number>; note: string;
}
export interface Setting { id: string; label: string; options: string[] }
interface ChargeBase { id: string; name: string; desc: string; tier: "main" | "advanced"; channel: Channel; codes: string[]; invoiceLines: number }
export interface SimpleCharge extends ChargeBase {
  kind: "simple"; unit: string; default: number | null; lo: number; hi: number; basis: string; pct: boolean; new: boolean;
}
export interface BuilderCharge extends ChargeBase {
  kind: "builder"; conds: Cond[]; units: Unit[]; settings: Setting[]; invalid: When[];
}
export type Charge = SimpleCharge | BuilderCharge;
export interface Category { id: string; name: string; desc: string; charges: Charge[] }
export interface ProposalSection { id: string; label: string; note: string }
export interface Catalog {
  version: string; categories: Category[];
  proposal: { sections: ProposalSection[]; categoryToSection: Record<string, string>; materials: string[];
              mergeGroups: { id: string; label: string; members: string[] }[] };
  defaultPreset: Record<string, ChargeSel>;   // "default template": the most common charges, pre-configured
  mapback: Mapback;                            // quote line -> existing system charge code
  systemCodes: Record<string, SystemCode>;     // billing-system item metadata (name, UOM, condition keys in use)
  standardTemplate: {                          // standard rates from all customers' price lists, as a ready quote
    customer: { company: string; code: string; channel: Channel }; title: string; note: string;
    selections: Record<string, ChargeSel>;
  };
}
export interface SystemCode { name: string; uom: string; category: string; keys: string[]; invoiceLines: number }
export interface UnitCodes {
  flat: string; initial?: string; second?: string;
  drivers?: Record<string, string | string[] | { range: string; incremental: string }>;
}
export interface Mapback {
  builder: Record<string, Record<string, UnitCodes>>;
  simple: Record<string, string>;
  newItems: Record<string, string>;
  notes: Record<string, string>;
  conds: Record<string, { key: string; values: Record<string, string>; note?: string }>;
  drivers: Record<string, { key: string; values?: Record<string, string>; byCharge?: Record<string, string> }>;
  chargeCondOverride: Record<string, Record<string, string>>;
}

// ---------------------------------------------------------------- quote selections (serializable, versioned)
export interface CondSel { on: boolean; values: string[]; text?: string }
export interface UnitSel {
  on: boolean;
  driver?: string | null;          // guided mode: one driver
  drivers?: string[];              // show-all mode: several drivers
  calc?: Record<string, string>;   // driverId -> "range" | "incremental"
  min?: string | null;
  second?: boolean;
  flatOtherwise?: boolean;        // rows a driver does not apply to keep a flat rate instead of being dropped
}
export interface ChargeSel {
  on: boolean;
  price?: number | null;           // simple charges
  conds: Record<string, CondSel>;
  units: Record<string, UnitSel>;
  prices: Record<string, number | null>;   // builder rate cells (key -> user price); absent = benchmark default
  settings: Record<string, string>;
  showAll?: boolean;
}
export interface QuoteHeader {
  title: string; facility: string; effectiveDate: string; validDays: number; preparedBy: string; notes: string;
}
export interface QuoteData { header: QuoteHeader; selections: Record<string, ChargeSel> }

export interface VersionMapping { summary: { total: number; mapped: number; newCondition: number; newItem: number }; lines: unknown[] }
export interface Version { v: number; savedAt: string; note: string; data: QuoteData; lineCount: number; mapping?: VersionMapping }
export type QuoteStatus = "draft" | "sent" | "accepted" | "archived";
export interface Quote {
  id: string; number: string; customerId: string; createdAt: string; updatedAt: string; status: QuoteStatus;
  draft: QuoteData; versions: Version[];
}
export interface Customer {
  id: string; code: string; company: string; contact: string; phone: string; email: string;
  address: string; city: string; state: string; zip: string; channel: Channel; createdAt: string;
}
export type HistoryType = "view" | "create" | "save-version" | "restore" | "export" | "print" | "customer-create" | "customer-edit" | "status";
export interface HistoryEvent { id: string; ts: string; type: HistoryType; quoteId?: string; customerId?: string; detail?: string }

// ---------------------------------------------------------------- engine output
export interface DimCell { id: string; label: string; value: string; kind: "cond" | "driver" }
export type LineCol = "p" | "first" | "add" | "min";
export interface QuoteLine {
  key: string;                // stable key: chargeId|unitId|cells|col
  chargeId: string; categoryId: string; unitId: string | null; unitLabel: string;
  dims: DimCell[]; col: LineCol; minBasis?: string;
  price: number | null; benchmark: number | null; pct: boolean; lo?: number; hi?: number;
}
