"""71 new charge ideas (Standard Rate Sheet - Common Items Coverage.xlsx, sheet "New charge ideas", 2026-10-01).

None has a billing-system code yet: every one is a new item in the charge-code mapback (setup list).
Placement rules:
  - tier: the sheet's Priority  High / Medium -> shown ("main"), Low -> folded under Advanced
  - std:  in the Standard Charge Template = High / Medium priority AND applies to most warehouse clients
          (ITEM technology products such as gates, cameras, RFID and GPS are quoted separately, not in the standard sheet)
  - fmt:  "" = USD amount, "pct" = fraction shown as %, "num" = plain number (e.g. months)
Prices: default = the sheet's Typical, lo / hi = Low / High. Price references name no client.
"""

# category ids added to the catalog (existing: setup, inbound, outbound, storage, returns, vas, other)
NEW_CATEGORIES = [
    {"id": "tech", "name": "Technology, AI & automation",
     "desc": "Systems, data, AI usage, support and robotics billed on top of warehouse services.",
     "i18n": {"zh": ("科技、AI 与自动化", "仓储服务之外按用量计费的系统、数据、AI、技术支持与机器人服务。"),
              "ja": ("テクノロジー・AI・自動化", "倉庫サービスに加えて請求するシステム、データ、AI 利用、サポート、ロボティクス。"),
              "es": ("Tecnología, IA y automatización", "Sistemas, datos, uso de IA, soporte y robótica facturados además de los servicios de almacén.")}},
    {"id": "security", "name": "Security, RFID & yard",
     "desc": "AI cameras, security gates, RFID, GPS, sensors and yard / dock systems.",
     "i18n": {"zh": ("安防、RFID 与堆场", "AI 摄像头、安防闸口、RFID、GPS、传感器以及堆场/月台系统。"),
              "ja": ("セキュリティ・RFID・ヤード", "AI カメラ、セキュリティゲート、RFID、GPS、センサー、ヤード/ドックシステム。"),
              "es": ("Seguridad, RFID y patio", "Cámaras con IA, puertas de seguridad, RFID, GPS, sensores y sistemas de patio / andén.")}},
    {"id": "terms", "name": "Commercial terms",
     "desc": "Contract terms: escalators, surcharges, termination and payment.",
     "i18n": {"zh": ("商务条款", "合同条款：年度调价、附加费、解约与付款。"),
              "ja": ("取引条件", "契約条件：年次改定、追加料金、解約、支払い。"),
              "es": ("Condiciones comerciales", "Condiciones del contrato: ajustes anuales, recargos, terminación y pago.")}},
]
CATEGORY_TO_SECTION = {"tech": "technology", "security": "security", "terms": "terms"}
NEW_SECTIONS = [  # inserted after "it" (technology, security) and at the end (terms)
    {"id": "technology", "label": "Technology, AI & Automation", "note": "Usage-based charges are billed monthly from system meters.",
     "i18n": {"zh": ("科技、AI 与自动化", "按用量计费的项目每月根据系统计量出账。"),
              "ja": ("テクノロジー・AI・自動化", "従量制の料金はシステムの計測値に基づき毎月請求します。"),
              "es": ("Tecnología, IA y automatización", "Los cargos por uso se facturan mensualmente según los medidores del sistema.")}},
    {"id": "security", "label": "Security, RFID & Yard", "note": "Hardware carries a one-year warranty; installation is quoted per site.",
     "i18n": {"zh": ("安防、RFID 与堆场", "硬件含一年保修；安装按现场报价。"),
              "ja": ("セキュリティ・RFID・ヤード", "ハードウェアは 1 年保証付き。設置は拠点ごとに見積もります。"),
              "es": ("Seguridad, RFID y patio", "El hardware tiene un año de garantía; la instalación se cotiza por sitio.")}},
    {"id": "terms", "label": "Commercial Terms", "note": "",
     "i18n": {"zh": ("商务条款", ""), "ja": ("取引条件", ""), "es": ("Condiciones comerciales", "")}},
]

MKT, EST, ITEMQ, VENDOR = "Market guides 2026", "Estimate", "ITEM quotation 2025", "Vendor list prices"

# (id, category, tier, std, fmt, default, lo, hi, basis, closest-code note,
#  en (name, desc, unit), zh, ja, es)
H, M_, L = "main", "main", "advanced"
ITEMS = [
    # ---------------------------------------------------------------- 1 Technology & data
    ("TC-ORDERFEE", "tech", H, True, "", 0.18, 0.10, 0.25, MKT, "Not covered: SYSTEM & MANAGEMENT FEE-0005 is per user / month.",
     ("Technology fee per order", "WMS, portal, tracking and integrations, recovered per shipped order.", "Order"),
     ("订单技术服务费", "按发货订单收取的 WMS、门户、追踪与系统对接费用。", "订单"),
     ("注文あたりテクノロジー料", "WMS・ポータル・追跡・連携のコストを出荷注文ごとに回収。", "注文"),
     ("Tarifa tecnológica por pedido", "WMS, portal, seguimiento e integraciones, cobrados por pedido enviado.", "Pedido")),
    ("TC-API", "tech", M_, False, "", 25, 10, 50, MKT, "",
     ("API access / API call fee", "Client systems calling WMS APIs (inventory, orders, tracking) above the included allowance.", "1,000 API calls"),
     ("API 接入/调用费", "客户系统调用 WMS API（库存、订单、追踪），超出包含额度部分。", "1,000 次 API 调用"),
     ("API 接続・呼び出し料", "顧客システムによる WMS API 呼び出し（在庫・注文・追跡）の無料枠超過分。", "API 呼び出し 1,000 回"),
     ("Acceso / llamadas a la API", "Llamadas de los sistemas del cliente a las API del WMS por encima de lo incluido.", "1,000 llamadas a la API")),
    ("TC-DATASTORE", "tech", H, False, "", 0.10, 0.05, 0.25, "Cloud cost basis + margin", "",
     ("System data storage", "Documents, POD / BOL, photos, video and attachments stored above the included allowance.", "GB / month"),
     ("系统存储空间费", "超出包含额度的单据、POD/BOL、照片、视频与附件存储。", "GB/月"),
     ("システムデータ保存料", "無料枠を超える書類・POD/BOL・写真・動画・添付ファイルの保存。", "GB/月"),
     ("Almacenamiento de datos del sistema", "Documentos, POD / BOL, fotos, video y adjuntos por encima de lo incluido.", "GB / mes")),
    ("TC-RETENTION", "tech", M_, False, "", 1200, 500, 3000, EST, "",
     ("Extended data retention / archive", "Keep transaction history, images and video beyond the standard retention period.", "Account / year"),
     ("数据延长保留/归档", "超出标准保留期限保存交易记录、图片与视频。", "账户/年"),
     ("データ長期保存・アーカイブ", "標準保存期間を超えて取引履歴・画像・動画を保管。", "アカウント/年"),
     ("Retención extendida / archivo", "Conservar historial, imágenes y video más allá del período estándar.", "Cuenta / año")),
    ("TC-REPORT", "tech", M_, True, "", 400, 150, 1000, MKT, "Partly covered: HANDLING-0217 ongoing IT support.",
     ("Custom report / dashboard development", "Build a client-specific report, KPI dashboard or scheduled export.", "Report (one-time)"),
     ("定制报表/看板开发", "为客户开发专属报表、KPI 看板或定时导出。", "报表（一次性）"),
     ("カスタムレポート・ダッシュボード開発", "顧客専用のレポート、KPI ダッシュボード、定期エクスポートを作成。", "レポート（1 回）"),
     ("Desarrollo de reporte / tablero a medida", "Reporte, tablero de KPI o exportación programada para el cliente.", "Reporte (único)")),
    ("TC-BIFEED", "tech", L, False, "", 250, 100, 500, EST, "",
     ("BI / data feed subscription", "Recurring data feed to the client's BI tool or data warehouse.", "Feed / month"),
     ("数据推送/BI 订阅", "定期向客户 BI 工具或数据仓库推送数据。", "数据源/月"),
     ("BI・データフィード契約", "顧客の BI ツールやデータウェアハウスへの定期データ連携。", "フィード/月"),
     ("Suscripción de datos / BI", "Envío periódico de datos al BI o data warehouse del cliente.", "Flujo / mes")),
    ("TC-CONNECTOR", "tech", M_, False, "", 75, 25, 150, MKT, "SU-ECOM covers the one-time connection setup.",
     ("Marketplace / e-commerce connector", "Ongoing connection per sales channel (Shopify, Amazon, Walmart ...).", "Channel / month"),
     ("电商平台连接器月费", "每个销售渠道（Shopify、Amazon、Walmart 等）的持续连接费。", "渠道/月"),
     ("EC モール連携月額", "販売チャネル（Shopify、Amazon、Walmart など）ごとの継続接続。", "チャネル/月"),
     ("Conector de marketplace / e-commerce", "Conexión continua por canal de venta (Shopify, Amazon, Walmart ...).", "Canal / mes")),
    ("TC-FACILITY", "tech", L, False, "", 300, 100, 750, EST, "Partly covered: SYSTEM & MANAGEMENT FEE-0004 enterprise environment.",
     ("Additional facility / entity in WMS", "Each extra site or legal entity configured for the client.", "Facility / month"),
     ("WMS 新增仓库/实体", "为客户额外配置的每个仓库或法人实体。", "仓库/月"),
     ("WMS 追加拠点・法人", "顧客向けに追加設定する拠点または法人ごと。", "拠点/月"),
     ("Instalación / entidad adicional en el WMS", "Cada sitio o entidad legal adicional configurada para el cliente.", "Instalación / mes")),
    ("TC-SANDBOX", "tech", L, False, "", 500, 200, 1000, EST, "",
     ("Sandbox / test environment", "Separate environment for client UAT or integration testing.", "Month"),
     ("测试环境", "供客户 UAT 或系统对接测试使用的独立环境。", "月"),
     ("サンドボックス・テスト環境", "顧客の UAT や連携テスト用の専用環境。", "月"),
     ("Entorno de pruebas", "Entorno separado para UAT o pruebas de integración del cliente.", "Mes")),
    ("TC-SSO", "tech", L, False, "", 250, 100, 500, EST, "",
     ("SSO / advanced security", "SAML single sign-on, audit logs and IP allow-listing for the client portal.", "Account / month"),
     ("单点登录/高级安全", "客户门户的 SAML 单点登录、审计日志与 IP 白名单。", "账户/月"),
     ("SSO・高度セキュリティ", "顧客ポータルの SAML シングルサインオン、監査ログ、IP 許可リスト。", "アカウント/月"),
     ("SSO / seguridad avanzada", "Inicio de sesión único SAML, registros de auditoría y lista de IP para el portal.", "Cuenta / mes")),
    ("TC-DEVICE", "tech", M_, False, "", 90, 40, 150, EST, "Partly covered: ACCESSORIAL-0028 rental equipment is hourly.",
     ("Handheld scanner / printer rental", "RF guns, mobile and label printers provided for dedicated operations.", "Device / month"),
     ("手持终端/打印机租赁", "为专属作业提供的 RF 扫描枪、移动打印机与标签打印机。", "设备/月"),
     ("ハンディ端末・プリンターレンタル", "専任オペレーション用の RF ガン、モバイル・ラベルプリンター。", "台/月"),
     ("Alquiler de escáner / impresora", "Pistolas RF e impresoras móviles y de etiquetas para operaciones dedicadas.", "Equipo / mes")),
    # ---------------------------------------------------------------- 2 AI usage
    ("TC-AITOKEN", "tech", H, False, "pct", 0.25, 0.15, 0.30, "Model API cost + 15-30% markup", "",
     ("AI token usage (LLM)", "Tokens used by AI features (assistant, document AI, agents), billed at cost plus markup.", "markup on AI token cost"),
     ("AI Token 用量", "AI 功能（助手、文档 AI、智能体）消耗的 Token，按成本加成收费。", "AI Token 成本加成"),
     ("AI トークン利用料（LLM）", "AI 機能（アシスタント、文書 AI、エージェント）が消費したトークンを原価＋マークアップで請求。", "AI トークン原価へのマークアップ"),
     ("Uso de tokens de IA (LLM)", "Tokens consumidos por funciones de IA (asistente, IA documental, agentes), al costo más margen.", "margen sobre el costo de tokens de IA")),
    ("TC-AIAGENT", "tech", M_, False, "", 1.00, 0.50, 2.00, "CX platform list prices", "",
     ("AI agent resolution (customer service)", "AI agent answers 'where is my order', returns and delivery questions.", "Resolved conversation"),
     ("AI 客服（按解决次数）", "AI 客服解答订单查询、退货与配送问题。", "已解决对话"),
     ("AI エージェント対応（カスタマーサービス）", "AI エージェントが注文状況・返品・配送の問い合わせに回答。", "解決した会話"),
     ("Resolución por agente de IA (servicio al cliente)", "El agente de IA responde dónde está mi pedido, devoluciones y entregas.", "Conversación resuelta")),
    ("TC-AIDOC", "tech", M_, False, "", 0.15, 0.05, 0.50, EST, "",
     ("AI document processing (OCR / extraction)", "Read BOL, POD, packing lists and invoices into the WMS / billing.", "Page"),
     ("AI 单据识别", "将 BOL、POD、装箱单与发票识别录入 WMS/计费系统。", "页"),
     ("AI 書類処理（OCR・抽出）", "BOL、POD、梱包明細、請求書を読み取り WMS・請求に取り込み。", "ページ"),
     ("Procesamiento de documentos con IA (OCR)", "Lectura de BOL, POD, listas de empaque y facturas hacia el WMS / facturación.", "Página")),
    ("TC-AIVISION", "tech", M_, False, "", 0.05, 0.02, 0.10, EST, "",
     ("AI vision QC / damage detection", "Camera-based check of cartons / pallets at receiving or packing.", "Scan"),
     ("AI 视觉质检/破损识别", "收货或包装环节用摄像头检查纸箱/托盘。", "次扫描"),
     ("AI 画像検品・破損検知", "入荷・梱包時にカメラでカートン・パレットを検査。", "スキャン"),
     ("Control de calidad por visión con IA", "Revisión con cámara de cajas / tarimas en recepción o empaque.", "Escaneo")),
    ("TC-AIPLAN", "tech", L, False, "", 1200, 500, 2500, EST, "",
     ("AI slotting / labor / demand forecasting", "Recurring optimisation of slotting, labor plans or replenishment.", "Facility / month"),
     ("AI 储位优化/预测", "定期优化储位、人力计划或补货。", "仓库/月"),
     ("AI ロケーション最適化・需要予測", "ロケーション、要員計画、補充の定期最適化。", "拠点/月"),
     ("Optimización con IA (ubicaciones / mano de obra / demanda)", "Optimización periódica de ubicaciones, planes de personal o reposición.", "Instalación / mes")),
    # ---------------------------------------------------------------- 3 AI camera & security
    ("SC-CAMLIC", "security", H, False, "", 21, 15, 33, VENDOR, "Not covered: HANDLING-0241 security charge is a pass-through.",
     ("AI camera license (video analytics)", "Cloud video and AI analytics license per camera (people / vehicle detection, alerts).", "Camera / month"),
     ("AI 摄像头使用费", "每个摄像头的云视频与 AI 分析授权（人员/车辆识别、告警）。", "摄像头/月"),
     ("AI カメラライセンス（映像解析）", "カメラごとのクラウド映像・AI 解析ライセンス（人・車両検知、アラート）。", "カメラ/月"),
     ("Licencia de cámara con IA (videoanalítica)", "Licencia de video en la nube y analítica por cámara (personas / vehículos, alertas).", "Cámara / mes")),
    ("SC-GATE", "security", H, False, "", 30000, 20000, 40000, ITEMQ, "",
     ("AI security gate subscription", "Gate software: plate / container OCR, check-in and entry control.", "Gate / year"),
     ("AI 安防闸口软件订阅", "闸口软件：车牌/箱号识别、登记与出入控制。", "闸口/年"),
     ("AI セキュリティゲート契約", "ゲートソフトウェア：ナンバー・コンテナ番号 OCR、受付、入場管理。", "ゲート/年"),
     ("Suscripción de puerta de seguridad con IA", "Software de acceso: OCR de placas / contenedores, registro y control de entrada.", "Puerta / año")),
    ("SC-BUILDING", "security", H, False, "", 50000, 35000, 65000, ITEMQ, "",
     ("AI building surveillance subscription", "Rooftop and perimeter AI camera coverage per building.", "Building / year"),
     ("AI 楼宇监控订阅", "每栋楼的屋顶与周界 AI 摄像头覆盖。", "栋/年"),
     ("AI 建物監視契約", "建物ごとの屋上・外周 AI カメラによる監視。", "棟/年"),
     ("Suscripción de vigilancia de edificio con IA", "Cobertura de cámaras con IA en techo y perímetro por edificio.", "Edificio / año")),
    ("SC-VIDRETAIN", "security", M_, False, "", 10, 5, 15, VENDOR, "",
     ("Video retention extension", "Keep footage 90 or 365 days instead of the standard 30.", "Camera / month"),
     ("视频延长保存", "录像保存 90 或 365 天（标准为 30 天）。", "摄像头/月"),
     ("映像保存期間の延長", "映像を標準の 30 日ではなく 90 日または 365 日保存。", "カメラ/月"),
     ("Retención extendida de video", "Conservar grabaciones 90 o 365 días en lugar de 30.", "Cámara / mes")),
    ("SC-FOOTAGE", "security", M_, False, "", 100, 50, 150, EST, "",
     ("Video footage retrieval / investigation", "Pull and review footage for a claim, theft or carrier dispute.", "Request"),
     ("视频调取/调查", "为索赔、失窃或承运商争议调取并查看录像。", "次请求"),
     ("映像の取り出し・調査", "クレーム、盗難、運送会社との紛争のため映像を確認。", "依頼"),
     ("Recuperación de video / investigación", "Extraer y revisar grabaciones por reclamo, robo o disputa con transportista.", "Solicitud")),
    ("SC-GATECAM", "security", M_, False, "", 4000, 3000, 5000, ITEMQ, "",
     ("AI gate camera - hardware + installation", "Additional or replacement gate camera including installation.", "Camera (one-time)"),
     ("闸口 AI 摄像头（含安装）", "新增或更换闸口摄像头，含安装。", "摄像头（一次性）"),
     ("ゲート AI カメラ（機器＋設置）", "ゲートカメラの追加・交換（設置込み）。", "カメラ（1 回）"),
     ("Cámara de acceso con IA (equipo + instalación)", "Cámara de acceso adicional o de reemplazo con instalación.", "Cámara (único)")),
    ("SC-ROOFCAM", "security", M_, False, "", 3500, 2500, 4500, ITEMQ, "",
     ("AI rooftop camera - hardware + installation", "Additional or replacement rooftop camera including installation.", "Camera (one-time)"),
     ("屋顶 AI 摄像头（含安装）", "新增或更换屋顶摄像头，含安装。", "摄像头（一次性）"),
     ("屋上 AI カメラ（機器＋設置）", "屋上カメラの追加・交換（設置込み）。", "カメラ（1 回）"),
     ("Cámara de techo con IA (equipo + instalación)", "Cámara de techo adicional o de reemplazo con instalación.", "Cámara (único)")),
    ("SC-INSTALL", "security", M_, False, "", 35000, 25000, 70000, ITEMQ, "",
     ("Security system installation project", "Site-wide cabling, mounts and network for gate and building cameras.", "Building (one-time)"),
     ("安防系统安装项目", "全场布线、支架与网络，用于闸口与楼宇摄像头。", "栋（一次性）"),
     ("セキュリティシステム設置工事", "ゲート・建物カメラ用の配線、取付、ネットワークを拠点全体で施工。", "棟（1 回）"),
     ("Proyecto de instalación de seguridad", "Cableado, soportes y red en todo el sitio para cámaras de acceso y edificio.", "Edificio (único)")),
    # ---------------------------------------------------------------- 4 RFID, GPS & IoT
    ("SC-RFIDSW", "security", H, False, "", 30000, 20000, 40000, ITEMQ, "",
     ("RFID software subscription", "Pallet, trailer and dock RFID tracking software per facility.", "Facility / year"),
     ("RFID 软件订阅", "每个仓库的托盘、挂车与月台 RFID 追踪软件。", "仓库/年"),
     ("RFID ソフトウェア契約", "拠点ごとのパレット・トレーラー・ドック RFID 追跡ソフト。", "拠点/年"),
     ("Suscripción de software RFID", "Software de rastreo RFID de tarimas, remolques y andenes por instalación.", "Instalación / año")),
    ("SC-RFIDREADER", "security", M_, False, "", 1500, 1000, 2000, ITEMQ, "",
     ("Forklift RFID reader - hardware", "RFID reader mounted on a forklift.", "Forklift (one-time)"),
     ("叉车 RFID 读写器硬件", "安装在叉车上的 RFID 读写器。", "叉车（一次性）"),
     ("フォークリフト RFID リーダー（機器）", "フォークリフトに取り付ける RFID リーダー。", "フォークリフト（1 回）"),
     ("Lector RFID para montacargas (equipo)", "Lector RFID montado en un montacargas.", "Montacargas (único)")),
    ("SC-RFIDINSTALL", "security", M_, False, "", 1500, 1000, 2000, ITEMQ, "",
     ("Forklift RFID reader - installation", "Install and commission a forklift RFID reader.", "Forklift (one-time)"),
     ("叉车 RFID 读写器安装", "安装并调试叉车 RFID 读写器。", "叉车（一次性）"),
     ("フォークリフト RFID リーダー（設置）", "フォークリフト RFID リーダーの設置と調整。", "フォークリフト（1 回）"),
     ("Lector RFID para montacargas (instalación)", "Instalación y puesta en marcha del lector RFID.", "Montacargas (único)")),
    ("SC-RFIDTAG", "security", M_, False, "", 0.12, 0.05, 0.20, ITEMQ, "Partly covered: ACCESSORIAL-0038 materials has no RFID material type.",
     ("RFID label / tag", "RFID label for a pallet, trailer or dock location.", "Label"),
     ("RFID 标签", "用于托盘、挂车或月台位置的 RFID 标签。", "张"),
     ("RFID ラベル・タグ", "パレット、トレーラー、ドック位置用の RFID ラベル。", "枚"),
     ("Etiqueta RFID", "Etiqueta RFID para tarima, remolque o andén.", "Etiqueta")),
    ("SC-GPS", "security", H, False, "", 27, 13.95, 60, ITEMQ, "",
     ("Truck GPS tracking subscription", "GPS tracking (optional dual dash cams) per truck.", "Truck / month"),
     ("车辆 GPS 追踪订阅", "每辆车的 GPS 追踪（可选双路行车记录仪）。", "车/月"),
     ("トラック GPS 追跡契約", "トラックごとの GPS 追跡（ドライブレコーダー 2 台オプション）。", "台/月"),
     ("Suscripción de rastreo GPS de camiones", "Rastreo GPS por camión (cámaras dobles opcionales).", "Camión / mes")),
    ("SC-GPSHW", "security", M_, False, "", 500, 300, 3000, ITEMQ, "",
     ("Truck GPS / dash cam - hardware + installation", "GPS unit (and cameras) installed per truck.", "Truck (one-time)"),
     ("车载 GPS/摄像头（含安装）", "每辆车安装 GPS 设备（及摄像头）。", "车（一次性）"),
     ("車載 GPS・ドラレコ（機器＋設置）", "トラックごとに GPS 機器（とカメラ）を設置。", "台（1 回）"),
     ("GPS / cámara de camión (equipo + instalación)", "Equipo GPS (y cámaras) instalado por camión.", "Camión (único)")),
    ("SC-IOT", "security", M_, False, "", 15, 5, 25, EST, "Partly covered: Temperature condition on storage codes prices the space, not the monitoring.",
     ("IoT sensor monitoring (temperature / humidity)", "Continuous monitoring, alerts and compliance log for sensitive goods.", "Sensor / month"),
     ("IoT 温湿度监控", "敏感货物的持续监控、告警与合规记录。", "传感器/月"),
     ("IoT センサー監視（温度・湿度）", "要管理品の常時監視、アラート、コンプライアンス記録。", "センサー/月"),
     ("Monitoreo IoT (temperatura / humedad)", "Monitoreo continuo, alertas y registro de cumplimiento para mercancía sensible.", "Sensor / mes")),
    ("SC-WARRANTY", "security", L, False, "pct", 0.15, 0.10, 0.20, EST, "",
     ("Hardware extended warranty", "Warranty after the standard one-year cover on cameras, readers and devices.", "of hardware price per year"),
     ("硬件延保", "摄像头、读写器与设备在标准一年保修之后的延保。", "硬件价格（每年）"),
     ("ハードウェア延長保証", "カメラ・リーダー・機器の標準 1 年保証後の延長保証。", "ハードウェア価格に対して（年）"),
     ("Garantía extendida de hardware", "Garantía después del año estándar en cámaras, lectores y equipos.", "del precio del hardware por año")),
    # ---------------------------------------------------------------- 5 Support & services
    ("TC-SUPPORT", "tech", H, False, "", 12000, 4500, 20000, ITEMQ, "Partly covered: SYSTEM & MANAGEMENT FEE-0003 IT maintenance.",
     ("Yearly remote tech support", "Remote support for licensed software and hardware, per facility or building.", "Year"),
     ("年度远程技术支持", "按仓库或楼宇提供的软硬件远程支持。", "年"),
     ("年間リモート技術サポート", "拠点・建物ごとのソフトウェア・ハードウェアのリモートサポート。", "年"),
     ("Soporte técnico remoto anual", "Soporte remoto de software y hardware por instalación o edificio.", "Año")),
    ("TC-ONSITE", "tech", H, False, "", 1200, 1000, 1600, ITEMQ, "",
     ("Onsite support (per day)", "Engineer on site, 8 hours included, travel billed separately.", "Day"),
     ("现场支持（按天）", "工程师到现场，含 8 小时，差旅另计。", "天"),
     ("オンサイトサポート（日額）", "エンジニアが現地対応、8 時間込み、交通費別途。", "日"),
     ("Soporte en sitio (por día)", "Ingeniero en sitio, 8 horas incluidas, viáticos aparte.", "Día")),
    ("TC-CONSULT", "tech", M_, False, "", 150, 125, 200, ITEMQ, "Partly covered: HANDLING-0217 ongoing support (UOM each).",
     ("Remote IT consultant / data service", "Out-of-scope IT or data projects.", "Hour"),
     ("远程 IT 顾问/数据服务", "范围外的 IT 或数据项目。", "小时"),
     ("リモート IT コンサル・データサービス", "契約範囲外の IT・データ案件。", "時間"),
     ("Consultor de TI remoto / servicio de datos", "Proyectos de TI o datos fuera del alcance.", "Hora")),
    ("TC-TRAVEL", "tech", M_, False, "pct", 0.0, 0.0, 0.10, ITEMQ, "",
     ("Travel expenses", "Consultant travel billed at actual cost (plus the markup shown).", "markup on actual travel cost"),
     ("差旅费", "顾问差旅按实际费用收取（另加所示加成）。", "实际差旅成本加成"),
     ("出張費", "コンサルタントの出張費を実費で請求（表示のマークアップを加算）。", "出張実費へのマークアップ"),
     ("Gastos de viaje", "Viajes del consultor facturados al costo real (más el margen indicado).", "margen sobre el costo real del viaje")),
    ("TC-AFTERHOURS", "tech", L, False, "pct", 0.50, 0.50, 1.00, "Industry 1.5-2x", "",
     ("After-hours / emergency support premium", "Support outside business hours or under a critical SLA.", "premium on the hourly / daily rate"),
     ("非工作时间/紧急支持加价", "工作时间以外或紧急 SLA 下的支持。", "按小时/天费率加价"),
     ("時間外・緊急サポート割増", "営業時間外または緊急 SLA でのサポート。", "時間・日額料金への割増"),
     ("Recargo por soporte fuera de horario / urgente", "Soporte fuera del horario laboral o con SLA crítico.", "recargo sobre la tarifa por hora / día")),
    ("TC-CSM", "tech", L, False, "", 4000, 1500, 9000, EST, "Partly covered: HANDLING-0191 customer service.",
     ("Dedicated customer success / solutions engineer", "Named customer success manager or engineer allocated to the account.", "Month"),
     ("专属客户成功/方案工程师", "为账户指定的客户成功经理或工程师。", "月"),
     ("専任カスタマーサクセス・ソリューションエンジニア", "アカウント専任のカスタマーサクセス担当またはエンジニア。", "月"),
     ("Ingeniero / gerente de éxito del cliente dedicado", "Gerente de éxito del cliente o ingeniero asignado a la cuenta.", "Mes")),
    # ---------------------------------------------------------------- 6 Robotics & automation
    ("TC-ROBOTCOUNT", "tech", H, False, "", 0.08, 0.03, 0.15, EST, "Partly covered: ACCESSORIAL-0010 cycle count is hourly manual counting.",
     ("Inventory robot / drone cycle count", "Autonomous drone or robot scans rack locations and reports exceptions.", "Location scanned"),
     ("盘点机器人/无人机盘点", "无人机或机器人自动扫描货架库位并报告差异。", "已扫描库位"),
     ("棚卸ロボット・ドローン循環棚卸", "ドローンやロボットがラック位置を自動スキャンし差異を報告。", "スキャン済みロケーション"),
     ("Conteo cíclico con robot / dron", "Un dron o robot escanea ubicaciones de rack y reporta diferencias.", "Ubicación escaneada")),
    ("TC-ROBOTPROG", "tech", M_, False, "", 4500, 2000, 8000, EST, "",
     ("Inventory robot program (RaaS)", "Recurring autonomous count program for a dedicated facility.", "Facility / month"),
     ("盘点机器人月度方案", "专属仓库的定期自动盘点方案。", "仓库/月"),
     ("棚卸ロボットプログラム（RaaS）", "専用拠点での定期的な自律棚卸プログラム。", "拠点/月"),
     ("Programa de robot de inventario (RaaS)", "Programa recurrente de conteo autónomo para una instalación dedicada.", "Instalación / mes")),
    ("TC-AMRPICK", "tech", M_, False, "", 0.05, 0.03, 0.06, "Pay-per-pick market rates", "",
     ("AMR-assisted pick (robot pick fee)", "Per-pick fee where picks run on collaborative robots.", "Pick"),
     ("AMR 辅助拣货费", "使用协作机器人完成拣货时按次收费。", "次拣货"),
     ("AMR 支援ピッキング料", "協働ロボットでピッキングする場合のピッキングごとの料金。", "ピッキング"),
     ("Picking asistido por AMR", "Tarifa por picking realizado con robots colaborativos.", "Picking")),
    ("TC-ROBOTFLEET", "tech", L, False, "", 1800, 1200, 2500, VENDOR, "",
     ("Dedicated robot fleet (RaaS)", "Robots dedicated to one client.", "Robot / month"),
     ("专属机器人车队", "专供单一客户使用的机器人。", "台/月"),
     ("専用ロボットフリート（RaaS）", "1 顧客専用のロボット。", "台/月"),
     ("Flota de robots dedicada (RaaS)", "Robots dedicados a un solo cliente.", "Robot / mes")),
    ("ST-ASRS", "storage", L, False, "", 4, 2, 6, "Market rates + estimate", "Partly covered: STORAGE INCOME-0013 capacity type has no AS/RS option.",
     ("Automated storage (AS/RS) bin", "Storage in goods-to-person / shuttle bins, a premium for density and speed.", "Bin / month"),
     ("自动化立库料箱存储", "货到人/穿梭车料箱存储，因密度与速度溢价。", "料箱/月"),
     ("自動倉庫（AS/RS）ビン保管", "GTP・シャトル方式のビン保管（高密度・高速の割増）。", "ビン/月"),
     ("Almacenamiento automatizado (AS/RS) por contenedor", "Almacenamiento en contenedores goods-to-person / shuttle, con prima por densidad y velocidad.", "Contenedor / mes")),
    ("SU-DIMS", "setup", M_, True, "", 1.25, 0.50, 2.00, EST, "Partly covered: ACCESSORIAL-0014 SKU setup does not include measuring.",
     ("SKU dimensioning & photo", "Capture dimensions, weight and photos per SKU at onboarding or on change.", "SKU"),
     ("SKU 量方拍照", "上线或变更时采集每个 SKU 的尺寸、重量与照片。", "SKU"),
     ("SKU 採寸・撮影", "導入時や変更時に SKU ごとの寸法・重量・写真を取得。", "SKU"),
     ("Medición y foto de SKU", "Registro de dimensiones, peso y fotos por SKU al iniciar o al cambiar.", "SKU")),
    # ---------------------------------------------------------------- 7 Yard & dock
    ("SC-YMS", "security", M_, False, "", 3000, 1500, 5000, VENDOR, "",
     ("Yard management subscription", "Trailer and container visibility, moves and dwell reporting.", "Facility / month"),
     ("堆场管理订阅", "挂车与集装箱可视化、移动与滞留报告。", "仓库/月"),
     ("ヤード管理契約", "トレーラー・コンテナの可視化、移動、滞留レポート。", "拠点/月"),
     ("Suscripción de gestión de patio", "Visibilidad de remolques y contenedores, movimientos y reporte de estadía.", "Instalación / mes")),
    ("SC-DOCKAPPT", "security", M_, False, "", 500, 175, 1300, VENDOR, "",
     ("Dock appointment scheduling portal", "Self-service carrier booking, reminders and no-show tracking.", "Facility / month"),
     ("月台预约平台", "承运商自助预约、提醒与爽约追踪。", "仓库/月"),
     ("ドック予約ポータル", "運送会社のセルフ予約、リマインダー、無断キャンセル管理。", "拠点/月"),
     ("Portal de citas de andén", "Reserva de citas por el transportista, recordatorios y control de ausencias.", "Instalación / mes")),
    ("SC-GATETXN", "security", L, False, "", 1.50, 0.50, 3.00, EST, "",
     ("Automated gate transaction (OCR check-in)", "Each truck in / out captured by the OCR / AI gate.", "Gate transaction"),
     ("闸口自动登记（按次）", "OCR/AI 闸口自动记录每次车辆进出。", "次闸口通行"),
     ("ゲート自動受付（OCR）", "OCR・AI ゲートがトラックの入出場を記録。", "ゲート通過"),
     ("Registro automático en puerta (OCR)", "Cada entrada / salida de camión registrada por la puerta OCR / IA.", "Transacción de puerta")),
    ("SC-EV", "security", L, False, "", 0.25, 0.15, 0.35, "Charging-as-a-service rates", "",
     ("EV charging for client vehicles", "Charging client or carrier electric vehicles on site.", "kWh"),
     ("电动车充电", "在场内为客户或承运商电动车充电。", "kWh"),
     ("EV 充電（顧客車両）", "顧客・運送会社の電気自動車を構内で充電。", "kWh"),
     ("Carga de vehículos eléctricos", "Carga de vehículos eléctricos del cliente o transportista en el sitio.", "kWh")),
    # ---------------------------------------------------------------- 8 Storage & inventory policy
    ("ST-AGED", "storage", H, True, "", 5, 2, 10, MKT, "Partly covered: Days Range condition on STORAGE INCOME-0004.",
     ("Long-term (aged) storage surcharge", "Inventory older than 180 / 365 days, on top of the storage rate.", "Pallet / month"),
     ("长期库龄仓储附加费", "库龄超过 180/365 天的库存，在仓储费基础上加收。", "托/月"),
     ("長期保管（滞留在庫）追加料金", "180 日・365 日を超える在庫に保管料に上乗せ。", "パレット/月"),
     ("Recargo por almacenamiento prolongado", "Inventario con más de 180 / 365 días, además de la tarifa de almacenaje.", "Tarima / mes")),
    ("ST-PEAK", "storage", M_, False, "pct", 0.35, 0.25, 0.50, MKT, "OT-PEAK is the per-order peak surcharge.",
     ("Peak-season storage premium", "Storage premium during peak season (October - January).", "of storage charges (Oct - Jan)"),
     ("旺季仓储加价", "旺季（10 月至次年 1 月）仓储加价。", "仓储费（10 月 - 1 月）"),
     ("繁忙期保管料割増", "繁忙期（10 月〜1 月）の保管料割増。", "保管料に対して（10 月〜1 月）"),
     ("Prima de almacenaje en temporada alta", "Prima sobre el almacenaje en temporada alta (octubre - enero).", "del almacenaje (oct - ene)")),
    ("ST-OVERSTOCK", "storage", L, False, "", 0.90, 0.44, 1.88, "Marketplace storage-utilization rates", "",
     ("Storage utilization / overstock surcharge", "When weeks of cover exceed the agreed limit (e.g. over 22 weeks).", "Cubic foot / month"),
     ("超储/库存周转附加费", "库存周转周数超过约定上限（如 22 周）时加收。", "立方英尺/月"),
     ("過剰在庫（保管効率）追加料金", "在庫週数が合意上限（例：22 週）を超えた場合。", "立方フィート/月"),
     ("Recargo por exceso de inventario", "Cuando las semanas de cobertura superan el límite acordado (p. ej. 22 semanas).", "Pie cúbico / mes")),
    ("ST-SKUFEE", "storage", M_, False, "", 1.00, 0.50, 2.00, MKT, "",
     ("Per-SKU storage / slow-mover fee", "Fee per active SKU, or per SKU with no movement in 90 days.", "SKU / month"),
     ("SKU 数量/滞销费", "按活跃 SKU 或 90 天无动销 SKU 收费。", "SKU/月"),
     ("SKU 単位保管料・低回転料", "アクティブ SKU ごと、または 90 日動きのない SKU ごとの料金。", "SKU/月"),
     ("Tarifa por SKU / baja rotación", "Por SKU activo o por SKU sin movimiento en 90 días.", "SKU / mes")),
    ("ST-HAZMAT", "storage", M_, True, "pct", 0.25, 0.15, 0.40, MKT, "",
     ("Hazmat / dangerous goods surcharge", "Segregated storage and handling of dangerous goods.", "surcharge on affected SKUs"),
     ("危险品附加费", "危险品的隔离存储与操作。", "适用 SKU 附加费"),
     ("危険物追加料金", "危険物の隔離保管と取り扱い。", "対象 SKU への追加料金"),
     ("Recargo por materiales peligrosos", "Almacenaje segregado y manejo de mercancías peligrosas.", "recargo sobre los SKU afectados")),
    ("ST-CAGE", "storage", M_, False, "", 10, 5, 20, EST, "Partly covered: HANDLING-0241 security charge.",
     ("High-value / secured cage storage", "Caged or CCTV-covered secure area.", "Pallet / month"),
     ("高货值/笼存储", "带围笼或监控覆盖的安全区域。", "托/月"),
     ("高額品・ケージ保管", "ケージまたは監視カメラ付きのセキュアエリア。", "パレット/月"),
     ("Almacenaje en jaula / alto valor", "Área segura enjaulada o con CCTV.", "Tarima / mes")),
    ("ST-BONDED", "storage", L, False, "", 750, 250, 2000, EST, "Partly covered: ACCESSORIAL-0008 bond document. Customs entries are billed per entry.",
     ("Bonded / FTZ storage & reporting", "Bonded inventory control and customs reporting.", "Month"),
     ("保税/FTZ 仓储与申报", "保税库存管理与海关申报。", "月"),
     ("保税・FTZ 保管と申告", "保税在庫の管理と税関への報告。", "月"),
     ("Almacenaje en depósito fiscal / FTZ", "Control de inventario en depósito y reportes aduanales.", "Mes")),
    ("ST-INSURANCE", "storage", L, False, "pct", 0.001, 0.0005, 0.0015, EST, "",
     ("Declared-value insurance", "Coverage above the standard warehouse legal liability.", "of declared value per month"),
     ("货值保险（超出法定责任）", "超出仓库标准法定责任的保障。", "申报货值（每月）"),
     ("申告価額保険", "倉庫の標準法定責任を超える補償。", "申告価額に対して（月）"),
     ("Seguro por valor declarado", "Cobertura por encima de la responsabilidad legal estándar del almacén.", "del valor declarado por mes")),
    ("ST-ANNUALCOUNT", "storage", L, False, "", 3500, 1500, 7500, MKT, "Partly covered: ACCESSORIAL-0010 is billed hourly.",
     ("Annual physical inventory (flat)", "Full wall-to-wall count quoted as one fee.", "Count"),
     ("年度全盘（固定价）", "全仓盘点，一口价报价。", "次盘点"),
     ("年次実地棚卸（固定料金）", "全数棚卸を一括料金で見積もり。", "回"),
     ("Inventario físico anual (tarifa fija)", "Conteo completo cotizado como una sola tarifa.", "Conteo")),
    ("ST-RECALL", "storage", L, False, "", 55, 45, 75, EST, "",
     ("Recall / quarantine management", "Hold, segregate and report lots under recall.", "Hour"),
     ("召回/隔离管理", "对召回批次进行冻结、隔离与报告。", "小时"),
     ("リコール・隔離管理", "リコール対象ロットの保留・隔離・報告。", "時間"),
     ("Gestión de retiro / cuarentena", "Retener, segregar y reportar lotes en retiro.", "Hora")),
    # ---------------------------------------------------------------- 9 Order & carrier
    ("OB-ORDERMOD", "outbound", M_, True, "", 6, 3, 12, MKT, "",
     ("Order modification after release", "Change address, items or carrier after the order is released to the floor.", "Change"),
     ("订单下发后修改", "订单下发作业后修改地址、商品或承运商。", "次修改"),
     ("出荷指示後の注文変更", "現場へ出荷指示後に住所・商品・運送会社を変更。", "変更"),
     ("Modificación de pedido después de liberado", "Cambio de dirección, artículos o transportista después de liberar el pedido.", "Cambio")),
    ("OB-DIMAUDIT", "outbound", L, False, "", 0.50, 0.25, 1.00, MKT, "",
     ("Dimensional-weight / carrier invoice audit", "Reconcile carrier dim-weight adjustments and audit carrier invoices.", "Order"),
     ("体积重/运费审计", "核对承运商体积重调整并审计运费账单。", "订单"),
     ("容積重量・運賃請求監査", "運送会社の容積重量調整を照合し運賃請求を監査。", "注文"),
     ("Auditoría de peso dimensional / facturas de flete", "Conciliar ajustes de peso dimensional y auditar facturas del transportista.", "Pedido")),
    ("OT-CARRIERSUR", "other", M_, True, "pct", 0.05, 0.03, 0.08, MKT, "Partly covered: Small Parcel-0005 freight markup.",
     ("Carrier surcharge pass-through", "Carrier surcharges (fuel, residential, delivery area) re-billed with a markup.", "markup on carrier surcharges"),
     ("承运商附加费转嫁", "承运商附加费（燃油、住宅、偏远地区）加成后转收。", "承运商附加费加成"),
     ("運送会社追加料金の転嫁", "運送会社の追加料金（燃料、住宅、配達エリア）をマークアップして請求。", "運送会社追加料金へのマークアップ"),
     ("Traslado de recargos del transportista", "Recargos del transportista (combustible, residencial, zona) refacturados con margen.", "margen sobre recargos del transportista")),
    ("RT-RTS", "returns", L, False, "", 6, 4, 10, MKT, "Partly covered: RMS-001 standard return.",
     ("Undeliverable / return-to-sender handling", "Process a package returned by the carrier as undeliverable.", "Package"),
     ("无法投递/退回处理", "处理承运商退回的无法投递包裹。", "包裹"),
     ("配達不能・差出人返送の処理", "運送会社から配達不能で返送された荷物を処理。", "荷物"),
     ("Manejo de paquetes no entregables", "Procesar un paquete devuelto por el transportista como no entregable.", "Paquete")),
    ("IN-UNSCHED", "inbound", L, False, "", 125, 75, 250, MKT, "Partly covered: ACCESSORIAL-0018 no ASN, HANDLING-0040 rush receipt.",
     ("Unscheduled / unannounced receipt", "Freight that arrives without an appointment.", "Receipt"),
     ("未预约到货", "未预约即到达的货物。", "收货单"),
     ("予約なし入荷", "予約なしで到着した貨物。", "入荷"),
     ("Recepción sin cita", "Carga que llega sin cita.", "Recepción")),
    ("TC-CARBON", "tech", L, False, "", 250, 100, 500, EST, "",
     ("Carbon / emissions report (Scope 3)", "Monthly shipment emissions report for the client's ESG reporting.", "Month"),
     ("碳排放报告", "为客户 ESG 披露提供的月度运输排放报告。", "月"),
     ("CO2 排出量レポート（スコープ 3）", "顧客の ESG 報告向けの月次出荷排出量レポート。", "月"),
     ("Reporte de emisiones de carbono (alcance 3)", "Reporte mensual de emisiones de envíos para el reporte ESG del cliente.", "Mes")),
    # ---------------------------------------------------------------- 10 Commercial terms
    ("CT-ENERGY", "terms", L, False, "pct", 0.02, 0.01, 0.03, MKT, "",
     ("Warehouse fuel / energy surcharge", "Index-linked surcharge on the warehouse bill.", "of the monthly warehouse bill"),
     ("仓库能源附加费", "与指数挂钩、按仓储账单收取的附加费。", "月度仓储账单"),
     ("倉庫燃料・エネルギー追加料金", "指数に連動して倉庫請求額に加算。", "月次倉庫請求額に対して"),
     ("Recargo de energía / combustible del almacén", "Recargo indexado sobre la factura del almacén.", "de la factura mensual del almacén")),
    ("CT-CARDFEE", "terms", M_, True, "pct", 0.03, 0.025, 0.035, MKT, "",
     ("Credit-card processing surcharge", "Applied when invoices are paid by credit card.", "of the card payment"),
     ("信用卡手续费", "以信用卡支付账单时收取。", "信用卡付款金额"),
     ("クレジットカード決済手数料", "請求書をクレジットカードで支払う場合に適用。", "カード決済額に対して"),
     ("Recargo por pago con tarjeta", "Se aplica cuando las facturas se pagan con tarjeta de crédito.", "del pago con tarjeta")),
    ("CT-ESCALATOR", "terms", H, True, "pct", 0.03, 0.0, 0.05, MKT, "",
     ("Annual rate escalator", "Automatic yearly increase on all rates at each contract anniversary.", "per year on all rates"),
     ("年度调价", "每个合同周年日自动上调全部费率。", "每年（全部费率）"),
     ("年次料金改定", "契約記念日ごとに全料金を自動改定。", "年あたり（全料金）"),
     ("Ajuste anual de tarifas", "Incremento automático anual de todas las tarifas en cada aniversario del contrato.", "por año sobre todas las tarifas")),
    ("CT-OFFBOARD", "terms", M_, True, "", 1.50, 0.50, 2.50, MKT, "Pallets leaving at contract end are typically billed $25 - $75 each in addition.",
     ("Inventory release / offboarding fee", "Pick and load all remaining inventory at contract end.", "Unit"),
     ("库存移出/退出费", "合同结束时拣选并装运全部剩余库存。", "件"),
     ("在庫引き揚げ（契約終了）料", "契約終了時に残在庫をすべてピッキングして積み込み。", "個"),
     ("Tarifa de salida de inventario", "Recoger y cargar todo el inventario restante al terminar el contrato.", "Unidad")),
    ("CT-EARLYTERM", "terms", M_, True, "num", 3, 2, 6, MKT, "",
     ("Early termination fee", "Due when the client exits before the end of the term.", "months of the monthly minimum"),
     ("提前解约费", "客户在合同期满前退出时收取。", "个月的月度最低消费"),
     ("中途解約料", "契約期間満了前に解約する場合に発生。", "か月分の月額最低料金"),
     ("Cargo por terminación anticipada", "Se cobra si el cliente sale antes del fin del plazo.", "meses del mínimo mensual")),
    ("CT-WAIVER", "terms", L, False, "num", 1, 1, 1, ITEMQ, "",
     ("First-month license fee waiver (clawback)", "First month free; due if the client terminates within two years.", "month of license fee"),
     ("首月免费（提前解约追回）", "首月免费；如两年内解约需补缴。", "个月授权费"),
     ("初月ライセンス料免除（解約時返還）", "初月無料。2 年以内に解約した場合は支払い。", "か月分のライセンス料"),
     ("Exención del primer mes (reembolsable)", "Primer mes gratis; se cobra si el cliente termina antes de dos años.", "mes de licencia")),
    ("CT-LATEINT", "terms", L, False, "pct", 0.01, 0.005, 0.015, ITEMQ, "Partly covered: LATE CHARGE-0001 (internal).",
     ("Late-payment interest", "Interest on overdue invoices.", "per month on the overdue balance"),
     ("逾期利息", "逾期账单的利息。", "每月（逾期余额）"),
     ("遅延損害金", "支払期日を過ぎた請求書への利息。", "月あたり（延滞残高）"),
     ("Intereses por pago tardío", "Intereses sobre facturas vencidas.", "por mes sobre el saldo vencido")),
]
assert len(ITEMS) == 71, len(ITEMS)
assert len({i[0] for i in ITEMS}) == 71


def charges_for(category_id):
    """simple-charge dicts for model_v3.simple(...) style lists, in sheet order."""
    out = []
    for cid, cat, tier, std, fmt, d, lo, hi, basis, _note, en, *_ in ITEMS:
        if cat != category_id:
            continue
        out.append({"id": cid, "kind": "simple", "name": en[0], "desc": en[1], "unit": en[2], "default": d, "lo": lo, "hi": hi,
                    "basis": basis, "channel": "Both", "tier": tier, "pct": fmt == "pct", "num": fmt == "num", "new": True, "codes": []})
    return out


NEW_ITEM_NAMES = {i[0]: i[10][0].upper() for i in ITEMS}
NOTES = {i[0]: i[9] for i in ITEMS if i[9]}
STANDARD = {i[0]: i[5] for i in ITEMS if i[3]}          # charge id -> standard-template price (the Typical rate)
MATERIALS = ["OT-CARRIERSUR"]                          # rate sheet: next to freight markup in Materials & Other Charges


def translations():
    """{lang: {english: translated}} for names, descriptions, units, categories and proposal sections."""
    out = {"zh": {}, "ja": {}, "es": {}}
    for i in ITEMS:
        for lang, tr in zip(("zh", "ja", "es"), i[11:14]):
            for en, x in zip(i[10], tr):
                out[lang][en] = x
    for c in NEW_CATEGORIES:
        for lang, (name, desc) in c["i18n"].items():
            out[lang][c["name"]] = name
            out[lang][c["desc"]] = desc
    for s in NEW_SECTIONS:
        for lang, (label, note) in s["i18n"].items():
            out[lang][s["label"]] = label
            if s["note"]:
                out[lang][s["note"]] = note
    return out
