# Rate card catalog v2 - industry-standard, webform-ready.
# One LN = one unique-content price line (same content with different prices across customers/codes is merged;
# the price becomes a user-entered field with a benchmark default).
#
# LN fields:
#   name     customer-facing line item          unit      billing unit
#   ch       channel: B2B | D2C | Both           tier      Core | Advanced
#   lo, hi   industry benchmark range (US 3PL, 2025-26 - model estimate, see README)
#   codes    system charge codes that bill this line; inc/exc = regex filters on price-list description
#   b2b/d2c  current UNIS template rate;  default/basis = explicit override of the benchmark default
#   desc     plain-language explanation (what is included / when it applies)
#   new      True = industry-standard line with no UNIS billing code yet

MIN = r"minimum|mini ?monthly|\bmin\b"

def LN(name, unit, ch, tier, lo, hi, codes=(), inc=None, exc=MIN, ratetype="Unit Price", b2b=None, d2c=None,
       default=None, basis=None, desc="", new=False, pct=False):
    return dict(name=name, unit=unit, ch=ch, tier=tier, lo=lo, hi=hi, codes=list(codes), inc=inc, exc=exc,
                ratetype=ratetype, b2b=b2b, d2c=d2c, default=default, basis=basis, desc=desc, new=new, pct=pct)

def SV(sid, name, what, trigger, notes, lines, extra_codes=()):
    return dict(id=sid, name=name, what=what, trigger=trigger, notes=notes, lines=lines, extra=list(extra_codes))

def H(n): return f"HANDLING-{n:04d}"
def S(n): return f"STORAGE INCOME-{n:04d}"
def A(n): return f"ACCESSORIAL-{n:04d}"

SECTIONS = []
def section(title, services): SECTIONS.append((title, services))

TV = [('Up to 32"', r'\b(19|20|22|23|24|25|26|27|28|29|32)"'), ('37" - 43"', r'\b(37|39|40|42|43)"'),
      ('46" - 50"', r'\b(46|47|48|49|50)"'), ('55" - 60"', r'\b(55|58|60)"'), ('65"', r'\b65"'),
      ('70" - 75"', r'\b(70|71|75)"'), ('80" - 86"', r'\b(80|82|85|86)"')]
OFF_CASE = [H(129), H(130), H(180)]
IT_ONBOARD = [H(206), H(235), H(205), H(218), H(189), H(190), H(229), H(230), H(202), H(222), H(220), H(248), H(244)]

# =============================================================== 1. ACCOUNT SETUP & SYSTEMS
section("1. ACCOUNT SETUP, SYSTEMS & INTEGRATION", [
 SV("AC-01", "Account Setup & Implementation",
    "One-time onboarding of a new client: kickoff and requirements, customer / facility setup in the WMS (WISE) and billing system (BNP), SOP build, user training, UAT and go-live support.",
    "One-time, per client (per facility)",
    "Industry norm is a one-time setup fee; waived or credited for large accounts. Integration development is priced separately (AC-04).",
    [LN("Account setup & implementation", "One-time", "Both", "Core", 500, 2500, IT_ONBOARD, default=1000, basis="Industry midpoint (no UNIS price data - setup is quoted today)",
        desc="Kickoff, requirements, WMS & billing setup, SOPs, training, UAT, go-live.")]),
 SV("AC-02", "Item / SKU Setup",
    "Load the client's item master (SKU, dims, weight, UPC, lot/serial flags) into the WMS at onboarding; set up SKUs added later.",
    "One-time import + per additional SKU",
    "Bulk import from a clean spreadsheet or integration is often included; manual SKU creation / dimensioning is charged.",
    [LN("Initial item-master import", "One-time", "Both", "Core", 0, 500, [H(200)], b2b=300, desc="Import of the full SKU list from a client-provided spreadsheet."),
     LN("Additional SKU setup (manual)", "SKU", "Both", "Core", 1, 6, [A(14)], b2b=5.75, desc="Each SKU created manually after go-live, incl. dims/weight capture.")]),
 SV("AC-03", "WMS / Client Portal Access",
    "Client access to the WMS portal for inventory visibility, order entry and reports; includes standard maintenance and support.",
    "Per user per month (or enterprise subscription)",
    "Current templates: $175/user/month (internal note: not listed on the card).",
    [LN("WMS user license & maintenance", "User / month", "Both", "Core", 100, 250, ["SYSTEM & MANAGEMENT FEE-0005"], inc=r"maintenance|user",
        desc="Portal login, standard reports, system maintenance."),
     LN("Enterprise WMS subscription (single entity)", "Entity / year", "Both", "Advanced", 10000, 25000, ["SYSTEM & MANAGEMENT FEE-0004"],
        default=18000, basis="UNIS price list (n=2)", desc="Unlimited users, dedicated environment - quoted.")],
    extra_codes=["SYSTEM & MANAGEMENT FEE-0003"]),
 SV("AC-04", "Integration Setup (EDI / API / e-commerce)",
    "Build and test the data connection with the client or its trading partners: EDI (940/945/856/850/810), FTP/CSV, or e-commerce platform / marketplace connectors (Shopify, Amazon, etc.).",
    "One-time per trading partner / platform",
    "EDI per trading partner is typically quoted; standard e-commerce connectors are low-cost or free.",
    [LN("EDI setup - per trading partner", "Trading partner", "B2B", "Core", 1500, 5000, [H(194), H(193)], default=2500, basis="Industry midpoint (UNIS quotes case by case)",
        desc="Mapping, testing and certification of the standard EDI document set for one partner."),
     LN("E-commerce platform / marketplace connection", "Connection", "D2C", "Core", 0, 500, [], new=True,
        desc="Connect a store / marketplace (Shopify, Amazon, Walmart, etc.) via standard connector."),
     LN("Retailer label & document setup", "Retailer", "B2B", "Advanced", 250, 1000, [H(244)],
        desc="Configure retailer-specific carton labels, packing slips and routing docs.")]),
 SV("AC-05", "EDI / FTP Transaction Fees",
    "Per-document charge for electronic transactions exchanged with the client or its partners (orders, ship confirmations, ASNs, receipts).",
    "Per document / transaction; VAN charges passed through",
    "Electronic documents replace manual-entry charges (IN-08 / OB-02).",
    [LN("EDI / FTP transaction", "Document", "Both", "Core", 0.25, 1.00,
        [H(102), H(103), H(99), H(48), H(49), H(50), H(1), H(2), H(45), H(46), H(47)], b2b=0.5,
        desc="Each 940 / 945 / 856 / 850 document or FTP file processed."),
     LN("EDI VAN charges (pass-through)", "% markup on cost", "Both", "Advanced", 0.0, 0.20, [H(98), H(100), H(101)], ratetype="Unit Price",
        default=0.20, basis="UNIS template (cost + 20%)", pct=True, desc="VAN provider cost re-billed plus markup.")]),
 SV("AC-06", "IT Support & Custom Development",
    "IT work requested by the client beyond standard system operation: custom reports, workflow changes, integration changes, troubleshooting of client-side data.",
    "Per IT hour (15-min increments)",
    "Templates differ today: B2B $150 vs D2C $200.",
    [LN("IT support / development", "Hour", "Both", "Core", 125, 200, [H(217)], b2b=150, d2c=200, desc="Billed in 15-minute increments, approved in advance.")]),
 SV("AC-07", "Account Management & Minimum Billing",
    "Recurring account-management fee (dedicated CSR, reporting, reviews) and/or a monthly minimum billing commitment across all services.",
    "Per month",
    "Common for smaller accounts to cover fixed cost. Storage-only minimum is in ST-08.",
    [LN("Account management fee", "Month", "Both", "Advanced", 250, 1500, [A(5), A(17), H(191)], ratetype="Unit Price", default=250, basis="UNIS price-list median $286 (n=43), rounded",
        desc="Dedicated account support, monthly reporting and business reviews."),
     LN("Monthly minimum billing (all services)", "Month", "Both", "Advanced", 1000, 5000, [], new=True,
        desc="If total monthly charges are below this amount, the difference is billed.")]),
])

# =============================================================== 2. INBOUND
section("2. INBOUND / RECEIVING", [
 SV("IN-01", "Container Unload - Floor Loaded",
    "Container or trailer arrives floor-loaded (loose cartons). UNIS unloads, sorts by SKU, builds pallets (1 SKU per pallet), counts, labels and receives into the WMS.",
    "Per container, priced by the number of cartons in the container (alternative: by container size)",
    "Excludes put-away (IN-04), pallets and wrap (MS-01). Shotgun-loaded containers add IN-06. System trigger can be 'Offload' or 'Billed Upon Receipt' - same price.",
    [LN("Floor-loaded container: up to 500 cartons", "Container", "B2B", "Core", 350, 550, OFF_CASE, inc=r"(?<![\d])0 ?- ?(499|500)\b", b2b=570),
     LN("Floor-loaded container: 501 - 1,000 cartons", "Container", "B2B", "Core", 400, 650, OFF_CASE, inc=r"\b50[01] ?- ?1,?000\b|(?<![\d])1 ?- ?1000\b|(?<![\d])0 ?- ?1000\b", b2b=610),
     LN("Floor-loaded container: 1,001 - 1,500 cartons", "Container", "B2B", "Core", 450, 700, OFF_CASE, inc=r"\b100[01] ?- ?1,?(499|500)\b|(?<![\d])0 ?- ?1500\b", b2b=640),
     LN("Floor-loaded container: 1,501 - 2,500 cartons", "Container", "B2B", "Core", 500, 800, OFF_CASE, inc=r"\b150[01] ?- ?2,?[05]00\b|\b(2000|1500) ?- ?2,?500\b", b2b=680),
     LN("Floor-loaded container: over 2,500 cartons (base)", "Container", "B2B", "Core", 600, 900, OFF_CASE, inc=r"over 2,?500|2500 ?- ?300[01]", b2b=715),
     LN("Each carton over 2,500", "Carton", "B2B", "Core", 0.20, 0.45, [H(127), H(128), H(179)], b2b=0.26),
     LN("Floor-loaded container - flat by size: 20'", "Container", "B2B", "Advanced", 300, 550, [H(126), H(178)], inc=r"20'", exc=MIN + r"|palletized|slip sheet"),
     LN("Floor-loaded container - flat by size: 40' / 40' HC", "Container", "B2B", "Advanced", 450, 800, [H(126), H(178)], inc=r"40'", exc=MIN + r"|palletized|slip sheet"),
     LN("Floor-loaded trailer - flat per 53' load", "Load", "B2B", "Advanced", 400, 750, [H(112), H(164), H(252), H(188)])],
    extra_codes=[H(130), H(181), H(125), H(177)]),
 SV("IN-02", "Palletized Receiving",
    "Freight arrives on pallets (LTL, truckload or palletized container). UNIS unloads each pallet, verifies count / SKU, labels and receives it into the WMS.",
    "Per pallet received, with a minimum per truckload / container",
    "Assumes 1 SKU per pallet. Mixed-SKU pallets that must be broken down add Sort & Segregation (IN-05) or re-palletizing (IN-07).",
    [LN("Palletized receiving - per pallet", "Pallet", "Both", "Core", 8, 15, [H(113), H(119), H(121), H(166), H(173), H(159), H(105), H(120), H(172)], b2b=10.5),
     LN("Minimum per truckload / container", "Load", "B2B", "Core", 250, 400, [H(113), H(121), H(119)], inc=r"minimum", exc=None, b2b=325),
     LN("Oversize / double-stacked pallet", "Pallet", "B2B", "Advanced", 12, 20, [H(118), H(171)])],
    extra_codes=[H(122), H(174)]),
 SV("IN-03", "Parcel & Loose-Carton Receiving",
    "Receive small-parcel, LTL or loose cartons: check in against the ASN, count, label if needed and receive into the WMS. Typical for e-commerce inventory.",
    "Per carton, per unit or per labor hour (choose one basis per client)",
    "D2C template 'Inbound and stow all products $45/hr' = hourly basis. Per-unit basis includes count to unit level.",
    [LN("Receiving - per labor hour", "Hour", "Both", "Core", 40, 60, [H(124), H(176)], exc=MIN, d2c=45, desc="Unload, count and stow; 15-min increments."),
     LN("Receiving - per carton", "Carton", "D2C", "Core", 0.50, 1.25, [H(107), H(161), H(104), H(158)], desc="Check-in and receive each carton (carton-level count)."),
     LN("Receiving - per unit", "Unit", "D2C", "Advanced", 0.15, 0.50, [H(114), H(167), H(106), H(160), H(111)], desc="Count and receive to each-level."),
     LN("Receiving - per cubic foot", "Cubic foot", "Both", "Advanced", 0.15, 0.40, [H(108), H(162), H(109), H(163)])],
    extra_codes=[H(115), H(168), H(117), H(170), H(165), H(116), H(169), H(195)]),
 SV("IN-04", "Put Away to Inventory",
    "Move received pallets / cartons from the dock to their storage location and confirm in the WMS.",
    "Per pallet",
    "Many 3PLs include put-away in receiving; UNIS bills it separately today.",
    [LN("Put away - per pallet", "Pallet", "Both", "Core", 3, 6, [H(53), H(54), H(55)], b2b=4.5)]),
 SV("IN-05", "Sort & Segregation",
    "Sort commingled cartons by SKU / lot / PO when a receipt contains more SKUs than the standard allowance (default: more than 5 SKUs per container).",
    "Per carton sorted (above the SKU threshold)",
    None,
    [LN("Sort & segregation - per carton", "Carton", "B2B", "Core", 0.15, 0.50, [H(29)], b2b=0.25),
     LN("Sort & segregation - per SKU over threshold", "SKU", "B2B", "Advanced", 10, 35, [H(28)])],
    extra_codes=[H(30), H(31), H(32)]),
 SV("IN-06", "Shotgun-Loaded Surcharge",
    "Additional labor when cartons are loosely thrown ('shotgunned') into the container instead of stacked.",
    "Per carton, on top of the container unload fee",
    None,
    [LN("Shotgun-loaded surcharge", "Carton", "B2B", "Core", 0.25, 0.60, [H(33), H(34), H(35)], b2b=0.35)]),
 SV("IN-07", "Re-Palletizing",
    "Rebuild damaged, overhanging or non-standard inbound pallets to warehouse standard, or build loose cartons onto pallets where not already included.",
    "Per pallet built",
    "Pallet and wrap materials bill under MS-01.",
    [LN("Re-palletize / pallet rebuild", "Pallet", "B2B", "Advanced", 6, 15, [H(81), H(82), H(83)])]),
 SV("IN-08", "Receiving Compliance & Admin",
    "Charges triggered by how the receipt arrives: missing / late ASN, receipts keyed manually by CSR, rush (same-day) receiving, missed dock appointments, and damage / OSD documentation.",
    "Per receipt / per occurrence / per hour",
    "Compliance charges are independent of receipt size.",
    [LN("No ASN / packing list (or ASN late)", "Receipt", "Both", "Core", 35, 75, [A(18)], b2b=50, desc="ASN required before arrival (template: 5 days before vessel arrival)."),
     LN("Manual receipt entry", "Receipt", "Both", "Core", 10, 25, [H(51), H(52), H(41), H(42)], desc="CSR keys the receipt when not sent electronically."),
     LN("Rush receipt (same-day)", "Receipt", "Both", "Advanced", 35, 75, [H(40)]),
     LN("Missed inbound appointment", "Occurrence", "B2B", "Advanced", 50, 150, [H(43), H(44)]),
     LN("OSD / damage documentation", "Hour", "Both", "Core", 45, 65, [H(219)], b2b=50, desc="Photos and report for overage, shortage, damage beyond routine notes."),
     LN("Lot / expiration date capture", "Carton", "Both", "Advanced", 0.10, 0.30, [], new=True, desc="Record lot number / expiry at receipt for FIFO / FEFO control.")]),
 SV("IN-09", "Transload & Cross-Dock",
    "Unload an inbound container and reload onto outbound trailers (transload), or receive and ship pallets through the dock without storage (cross-dock).",
    "Per container / per pallet",
    "Configured in the system but not invoiced in Sep-26.",
    [LN("Transload - 20' container", "Container", "B2B", "Advanced", 250, 450, [H(23)], inc=r"20'"),
     LN("Transload - 40' / 40' HC / 53'", "Container", "B2B", "Advanced", 350, 650, [H(23), H(26), H(27), H(17), H(19)], inc=r"40'|45'|53'|all container|cases"),
     LN("Transload - per pallet", "Pallet", "B2B", "Advanced", 6, 12, [H(11), H(16), H(18), H(4)]),
     LN("Cross-dock - per pallet", "Pallet", "B2B", "Advanced", 5, 12, [H(157)])],
    extra_codes=[H(n) for n in range(3, 28) if n not in (4, 11, 16, 17, 18, 19, 23, 26, 27)]),
])

# =============================================================== 3. STORAGE
section("3. STORAGE", [
 SV("ST-01", "Pallet Storage",
    "Store palletized product in a pallet position (rack or floor). Standard position: 1 SKU, footprint up to 40x48 in, height up to 60 in.",
    "Per pallet position per month. Billed at receipt for the first period and on the 1st of each month thereafter",
    "Initial and recurring storage are the SAME price line - the billing method (full / half month at receipt, monthly / semi-monthly cycle) is a quote setting, not a separate price. A partial pallet in a full position bills as one position.",
    [LN("Pallet position - standard (per month)", "Pallet / month", "Both", "Core", 12, 30, [S(4), S(17)], inc=r"monthly|^rate by unit", b2b=22, d2c=22),
     LN("Floor-stacked pallet (stackable 2-high+)", "Pallet / month", "B2B", "Advanced", 10, 20, [S(11), S(24)], inc=r"\b[2-9] high|bulk"),
     LN("Oversize / tall pallet (single-stack, >60 in)", "Pallet / month", "B2B", "Advanced", 25, 45, [S(11), S(24)], inc=r"\b1 high"),
     LN("Oversize pallet by footprint", "Pallet / month", "B2B", "Advanced", 18, 35, [S(9), S(22)])]),
 SV("ST-02", "Bin & Shelf Storage",
    "Store small or slow-moving SKUs in shelf bins instead of full pallet positions - typical for e-commerce.",
    "Per location per month (billed at receipt and on the 1st)",
    "Single SKU per bin. Price lists do not record bin size, so template values are used as the default.",
    [LN("Small bin (per month)", "Bin / month", "D2C", "Core", 3, 6, [S(13), S(26)], inc=r"small bin", d2c=4, desc="Approx. up to 1 cu ft."),
     LN("Large bin / shelf (per month)", "Bin / month", "D2C", "Core", 6, 12, [S(13), S(26)], inc=r"large bin", d2c=8, desc="Approx. 1 - 6 cu ft / half shelf.")]),
 SV("ST-03", "Cubic-Foot Storage",
    "Storage billed on the cubic feet of inventory on hand, measured on a set day each month - common for e-commerce with many small SKUs.",
    "Per cubic foot per month",
    "Alternative to ST-02; quote one basis per client.",
    [LN("Storage - per cubic foot (per month)", "Cu ft / month", "D2C", "Core", 0.30, 0.85, [S(2), S(15)])],
    extra_codes=[S(3), S(16), S(1), S(14), S(5), S(6), S(18), S(19)]),
 SV("ST-04", "Dedicated Space",
    "Dedicated floor area reserved for the client (caged / blocked area), or storage billed on item footprint.",
    "Per square foot per month, usually with a monthly minimum",
    None,
    [LN("Dedicated space - per sq ft (per month)", "Sq ft / month", "B2B", "Advanced", 0.90, 1.75, [S(8), S(21), S(7), S(20)], inc=r"monthly|square", exc=MIN)],
    extra_codes=[S(28), "Sublease Revenue-0001"]),
 SV("ST-05", "TV / Display Storage (by screen size)",
    "Storage of TVs and monitors billed per unit by screen size.",
    "Per unit per month",
    "Specialty line (high UNIS usage). 98\"+ excluded: current price data is inconsistent - quote per request.",
    [LN(f"TV storage {lbl}", "Unit / month", "B2B", "Core", None, None, [S(10), S(23)], inc=rx) for lbl, rx in TV]),
 SV("ST-06", "Long-Term Storage Surcharge",
    "Surcharge on inventory aged beyond the agreed threshold (default 180 days) to encourage turns.",
    "% on top of the base storage rate, per month",
    "System supports this through the 'Days Range' condition on storage codes.",
    [LN("Aged inventory (> 180 days) surcharge", "% of storage", "Both", "Advanced", 0.25, 1.00, [], default=0.50, basis="Industry midpoint", pct=True, new=True)]),
 SV("ST-07", "Yard & Container Storage",
    "Loaded or empty containers / trailers parked in the UNIS yard beyond free time (incl. container layover), and yard-truck moves.",
    "Per container per day; yard moves per move",
    "Free time per contract (template: 24 hours after the container is empty).",
    [LN("Yard / container storage (per day)", "Container / day", "B2B", "Advanced", 25, 50, ["YARD-0001", "YARD-0002", S(27), S(12), S(25)], b2b=35),
     LN("Yard hostler move", "Move", "B2B", "Advanced", 50, 125, [H(250)], default=91, basis="UNIS usage (69 invoice lines)"),
     LN("Yard hostler - weekend (per hour)", "Hour", "B2B", "Advanced", 90, 150, [H(251)], default=129.6, basis="UNIS usage (31 invoice lines)"),
     LN("Outside-carrier container handling", "Container", "B2B", "Advanced", 100, 250, ["OTHERS-0003", "TRANSPORTATION-0001"], b2b=175,
        desc="Gate / scheduling / paperwork when inbound drayage is not by UNIS (not a drayage charge).")]),
 SV("ST-08", "Monthly Storage Minimum",
    "Minimum monthly storage charge billed when actual storage is below the committed level.",
    "Per month",
    "Configured as a 'Minimum' condition on storage codes (no separate code). Initial + recurring storage can share one combined minimum.",
    [LN("Monthly storage minimum", "Month", "B2B", "Core", 2500, 15000, [S(4), S(13)], inc=r"minimum", exc=None, b2b=15000)]),
])

# =============================================================== 4. OUTBOUND B2B
section("4. OUTBOUND - B2B / RETAIL / WHOLESALE", [
 SV("OB-01", "B2B Order Processing",
    "Release a wholesale / retail order, generate BOL and packing list, stage and confirm shipment.",
    "Per order (plus picking and accessorials actually used)",
    "An order bills as order processing + picking + accessorials used - never one flat fee.",
    [LN("B2B order - LTL / truckload (incl. BOL & packing list)", "Order", "B2B", "Core", 10, 25, [H(93)], inc=r"truckload|\bLTL\b|regular order", exc=MIN + r"|small parcel|drop ?ship|b2c", b2b=22),
     LN("B2B order - small parcel (incl. packing list)", "Order", "B2B", "Core", 2.5, 6, [H(93)], inc=r"small parcel"),
     LN("B2B order - per order line (alternative)", "Order line", "B2B", "Advanced", 0.5, 3, [H(91)])],
    extra_codes=[H(90), H(92), H(94)]),
 SV("OB-02", "B2B Picking",
    "Pick full pallets, full cartons, or units from open cartons for a wholesale / retail order.",
    "Per pallet / per carton / per unit actually picked",
    "Pallet pick bills only for an intact pallet shipped as-is. Breaking a pallet down = pallet pick + carton picks + labor.",
    [LN("Full pallet pick", "Pallet", "B2B", "Core", 6, 15, [H(67), H(77), H(60), H(75)], b2b=10.5),
     LN("Carton (case) pick - up to 50 lbs", "Carton", "B2B", "Core", 0.50, 1.75, [H(63), H(72)], inc=r"0 ?- ?30 lbs|0 ?- ?60 lbs|^rate by unit$|regular order", exc=MIN + r"|drop ?ship", b2b=1.05, d2c=1.65),
     LN("Heavy / bulky carton pick (over 50 lbs)", "Carton", "B2B", "Core", 3, 12, [H(72)], inc=r"over 60"),
     LN("Unit pick from open carton (B2B)", "Unit", "B2B", "Core", 0.40, 1.25, [H(69), H(68)], inc=r"regular|b2b|^rate by unit$", exc=MIN + r"|drop ?ship|b2c"),
     LN("Inner-pack pick", "Inner", "B2B", "Advanced", 0.40, 1.00, [H(64)], exc=MIN + r"|drop ?ship|b2c"),
     LN("Minimum picking charge per order", "Order", "B2B", "Advanced", 15, 25, [H(63)], inc=r"minimum", exc=None, d2c=20)],
    extra_codes=[H(76), H(57), H(70), H(71), H(78), H(79), H(80), H(65), H(66)]),
 SV("OB-03", "B2B Shipping Preparation",
    "Prepare B2B shipments to the retailer's standard: UCC-128 carton labels, pallet build and wrap, routing / appointment requests through retailer portals, and loading.",
    "Per label / per pallet / per BOL / per load",
    "Pallet materials in MS-01.",
    [LN("Carton label (UCC-128 / shipping label) print & apply", "Label", "Both", "Core", 0.25, 0.75, [H(155), H(156)], b2b=0.6, d2c=0.4),
     LN("Routing / retailer compliance (per BOL)", "BOL", "B2B", "Core", 7.5, 25, [H(239)], b2b=12.5),
     LN("Outbound pallet build & wrap (mixed pallets)", "Pallet", "B2B", "Core", 5, 12, [H(142), H(136), H(146)], desc="Build shipping pallet from picked cartons, wrap, label."),
     LN("Floor-load outbound container / trailer", "Container", "B2B", "Advanced", 300, 650, [H(151), H(153), H(148), H(149)])],
    extra_codes=[H(n) for n in range(131, 155) if n not in (136, 142, 146, 148, 149, 151, 153)] + [H(197)]),
])

# =============================================================== 5. OUTBOUND D2C
section("5. OUTBOUND - D2C / E-COMMERCE", [
 SV("DC-01", "E-commerce Order Fulfillment",
    "Process a consumer order: pick, pack into a mailer or box, print the carrier label and hand to the carrier.",
    "Per order + per item picked; weight band surcharges",
    "Industry alternative is an all-in 'first item / additional item' pick & pack fee - offered as Advanced.",
    [LN("E-com order processing (incl. pack & label)", "Order", "D2C", "Core", 1.50, 3.50, [H(93), H(89)], inc=r"drop ?ship|b2c", b2b=2, d2c=2),
     LN("Each pick (per item)", "Item", "D2C", "Core", 0.25, 0.75, [H(69), H(64), H(68)], inc=r"drop ?ship|b2c", b2b=0.5, d2c=0.5),
     LN("Order weight surcharge: 5 - 10 lbs", "Order", "D2C", "Core", 0.75, 2.00, [H(89)], inc=r"over|5 ?- ?10", default=1.00, basis="UNIS D2C template ($3 vs $2 base)",
        desc="Added to the base order fee for packages 5 - 10 lbs."),
     LN("Order weight surcharge: 10 - 30 lbs", "Order", "D2C", "Advanced", 1.50, 4.00, [], new=True),
     LN("Pick & pack - first item (all-in alternative)", "Order", "D2C", "Advanced", 2.50, 3.75, [H(58), H(59), H(61), H(62), H(56)], inc=r"first"),
     LN("Pick & pack - each additional item", "Item", "D2C", "Advanced", 0.50, 1.00, [], inc=r"additional"),
     LN("Small-parcel packing - per carton (multi-box)", "Carton", "D2C", "Advanced", 0.35, 1.00, [H(85), H(84)])],
    extra_codes=[H(73), H(74), H(86), H(87)]),
 SV("DC-02", "Packaging & Presentation Add-Ons",
    "Optional packaging steps on consumer orders: packing slip, branded box / tape, inserts, fragile wrap, gift wrap, overbox, void fill.",
    "Per order / per item / per box",
    "Material cost billed separately (MS-02) unless stated. Minimum volumes may apply (template: branded packaging 2,000 orders/month).",
    [LN("Packing slip", "Order", "D2C", "Core", 0.10, 0.35, [A(23)], d2c=0.35),
     LN("Branded packaging (incl. tape)", "Order", "D2C", "Core", 0.25, 0.75, [], d2c=0.35, new=True),
     LN("Insert / flier / sticker", "Item", "D2C", "Core", 0.10, 0.25, [], d2c=0.15, new=True),
     LN("Fragile / tissue / bubble wrap", "Item", "D2C", "Core", 0.35, 1.00, [], d2c=0.5, new=True),
     LN("Overbox (corrugate)", "Box", "D2C", "Core", 0.50, 1.50, ["ACC-0003", "OVERBOX"], d2c=0.5),
     LN("Void fill / dunnage", "Order", "D2C", "Core", 0.15, 0.50, ["DUNNAGE"], d2c=0.5),
     LN("Gift wrap / gift message", "Order", "D2C", "Advanced", 1.00, 3.00, [], new=True)]),
 SV("DC-03", "Marketplace Prep (Amazon FBA / WFS)",
    "Prepare inventory to marketplace standards before shipping to their fulfillment centers.",
    "Per unit",
    "Bundling / multi-packs use Kitting (VS-01).",
    [LN("FNSKU / marketplace label", "Unit", "Both", "Core", 0.20, 0.50, [H(184)]),
     LN("Poly bag + suffocation warning", "Unit", "Both", "Advanced", 0.35, 0.75, [], new=True),
     LN("SKU conversion / relabel", "Unit", "Both", "Advanced", 0.25, 0.75, ["ACC-0004"])]),
 SV("DC-04", "Shipping & Postage",
    "Carrier postage / freight arranged by UNIS, handling of client-owned carrier accounts, and post-order address changes.",
    "Cost + markup / per order / per occurrence",
    None,
    [LN("Postage & freight (UNIS accounts)", "% markup on cost", "Both", "Core", 0.0, 0.20, ["Small Parcel-0003", "Small Parcel-0004", "Small Parcel-0005", "TRANSPORTATION-0002"],
        default=0.20, basis="UNIS template (postage cost + 20%)", pct=True),
     LN("Client's own carrier account (3rd-party postage)", "Order", "D2C", "Core", 0.25, 1.00, [H(182)], d2c=0.75),
     LN("Address correction / change after release", "Occurrence", "D2C", "Core", 2, 5, [A(37)], d2c=2.5, desc="Plus any carrier correction fee."),
     LN("International / customs manifest", "Order", "D2C", "Advanced", 0.50, 2.00, [A(13)], d2c=0.5),
     LN("Peak-season surcharge (Nov - Dec)", "Order", "D2C", "Advanced", 0.25, 0.75, [], new=True)]),
])

# =============================================================== 6. ORDER ACCESSORIALS (both channels)
section("6. ORDER ACCESSORIALS (B2B & D2C)", [
 SV("OA-01", "Order Exceptions",
    "Charges triggered by how an order is placed or changed: manual entry by CSR, rush same-day processing, cancellation after release, missed carrier appointment.",
    "Per order / per occurrence",
    "Cut-off times and cancellation windows to be defined in the SOW.",
    [LN("Manual order entry", "Order", "Both", "Core", 5, 20, [H(96), H(97)], b2b=15, d2c=15),
     LN("Rush order (after cut-off, same day)", "Order", "Both", "Core", 25, 75, [H(88)], b2b=50, d2c=50),
     LN("Cancelled order - after picking", "Order", "Both", "Core", 5, 25, [A(2), A(7)], b2b=10, d2c=10, desc="Plus return-to-stock labor at the hourly rate."),
     LN("Cancelled order - before picking", "Order", "Both", "Advanced", 0, 10, [A(1)], desc="Often waived in the industry."),
     LN("Missed outbound appointment", "Occurrence", "B2B", "Advanced", 50, 150, [H(95)], b2b=50)]),
 SV("OA-02", "Documents",
    "Prepare shipping / customs paperwork on request (international BOL, commercial invoice, customs-bond documents) and provide copies or scans.",
    "Per document / per page",
    "Standard BOL and packing list are included in order processing.",
    [LN("Custom shipping / customs document", "Document", "Both", "Core", 5, 15, [A(9), A(6), A(8)], b2b=10, d2c=10),
     LN("Copies / document scans", "Page", "Both", "Core", 0.25, 1.00, [A(26), A(12)], b2b=1, d2c=1)]),
])

# =============================================================== 7. RETURNS
section("7. RETURNS", [
 SV("RT-01", "Returns Processing",
    "Receive a returned package, open and minor-inspect, photograph, record condition and report to the client; hold for disposition instructions.",
    "D2C: per package + per item.  B2B: per carton / per pallet",
    "Detailed grading, restock and disposal are separate lines below.",
    [LN("Return received - per package", "Package", "D2C", "Core", 2.00, 4.00, ["RMS-001"], d2c=2.5),
     LN("Return processed - per item", "Item", "D2C", "Core", 0.50, 1.50, [H(39)], d2c=0.75),
     LN("B2B return - per carton", "Carton", "B2B", "Core", 1.50, 4.00, [H(36)]),
     LN("B2B return - per pallet", "Pallet", "B2B", "Advanced", 8, 20, [H(38)]),
     LN("Detailed inspection / grading", "Item", "Both", "Advanced", 1.00, 3.00, ["RMS-002", "RMS-003"]),
     LN("Restock to available inventory", "Item", "Both", "Advanced", 0.50, 1.50, ["RMS-006", H(236)]),
     LN("Disposal / destruction", "Item", "Both", "Advanced", 0.25, 1.00, [A(11)], desc="Plus hauling at cost."),
     LN("Drop-ship re-processing (re-ship)", "Unit", "D2C", "Advanced", 2.50, 5.00, [H(192)])],
    extra_codes=[H(37), "RMS-004"]),
])

# =============================================================== 8. VAS & LABOR
section("8. VALUE-ADDED SERVICES & LABOR", [
 SV("VS-01", "Kitting & Bundling",
    "Assemble components into a kit, gift set or multi-pack per client work order, incl. component pick and finished-kit put-away.",
    "Per kit (simple: up to 3 components) or hourly for complex assembly",
    "Always in addition to receiving / storage / pick of the finished kit.",
    [LN("Kit / bundle assembly", "Kit", "Both", "Core", 0.75, 2.50, [H(208), H(207)], default=1.85, basis="UNIS usage-sheet average (17 customers)")],
    extra_codes=[H(187), H(185), H(186)]),
 SV("VS-02", "Labeling & Tracking",
    "Apply or replace product / carton labels, and capture serial numbers or photos when required by the client.",
    "Per label / per scan / per photo",
    "Shipping labels are in OB-03.",
    [LN("Item label apply / relabel", "Unit", "Both", "Core", 0.20, 0.60, ["ACC-0002", H(210), "RELABELING", H(209), H(232)]),
     LN("Serial number capture", "Scan", "Both", "Core", 0.25, 1.25, [H(243), H(211)], b2b=1.25, d2c=1.25),
     LN("Photo on request", "Photo", "Both", "Core", 0.50, 2.00, [A(27), "RMS-005"])]),
 SV("VS-03", "Warehouse Labor",
    "Work outside standard handling (rework, repack, sorting, QC, special projects, consolidation, clean-up). The task is recorded on the work order so the invoice shows what the hours were for.",
    "Per labor hour, 15-minute increments",
    "One hourly rate for all tasks (same content, different task label) - task selected in the quote / work order.",
    [LN("Warehouse labor - regular", "Hour", "Both", "Core", 45, 65, [H(199), "HOURLY LABOR", H(213), A(32), A(29), H(238), H(246), H(240), H(204), H(227), H(212), H(201), H(221), "OTHERS-0002", H(226), H(187)], b2b=50, d2c=50),
     LN("Warehouse labor - overtime / weekend", "Hour", "Both", "Core", 65, 95, [H(225), H(223)], b2b=75, d2c=75),
     LN("Supervisor / overnight clerk", "Hour", "Both", "Advanced", 55, 85, [H(224)])],
    extra_codes=[H(233)]),
 SV("VS-04", "Inventory Control",
    "Client-requested cycle counts and full physical inventories, and inventory consolidation.",
    "Per labor hour",
    "System-directed counts for UNIS accuracy are not billed.",
    [LN("Cycle count / physical inventory", "Hour", "Both", "Core", 45, 65, [A(10)], b2b=50, d2c=50)]),
])

# =============================================================== 9. MATERIALS
section("9. MATERIALS & SUPPLIES", [
 SV("MS-01", "Pallets & Pallet Securing",
    "Pallets supplied by UNIS and materials to secure pallets for shipment.",
    "Per pallet",
    "Pallets: fixed price or market rate + 20%.",
    [LN("Pallet - Grade A (new / premium 40x48)", "Pallet", "B2B", "Core", 15, 25, [], b2b=18.75, d2c=18.75, new=True),
     LN("Pallet - Grade B (recycled 40x48)", "Pallet", "B2B", "Core", 8, 15, [], b2b=14.75, d2c=14.75, new=True),
     LN("Stretch wrap", "Pallet", "B2B", "Core", 3, 8, [A(33)], b2b=5.7, d2c=5.7),
     LN("Plastic strapping", "Pallet", "B2B", "Advanced", 4, 8, ["OTHERS-0004"], b2b=6.5, d2c=6.5),
     LN("Corner boards", "Pallet", "B2B", "Advanced", 4, 8, [], b2b=6.5, d2c=6.5, new=True),
     LN("Slip sheet / top sheet", "Pallet", "B2B", "Advanced", 2, 6, ["SLIPSHEET", "OTHERS-0005"])]),
 SV("MS-02", "Packaging & Supplies (cost-plus)",
    "Boxes, mailers, tape, labels and other supplies purchased by UNIS for the client.",
    "Cost + markup",
    None,
    [LN("Packaging & supplies", "% markup on cost", "Both", "Core", 0.10, 0.25, ["Freight-0001", A(35), A(19), A(22), A(38)], ratetype="Mark Up", pct=True)]),
 SV("MS-03", "Facility Pass-Throughs",
    "Client-specific costs re-billed: rental equipment, waste removal, utilities, security.",
    "At cost + markup, or quoted",
    None,
    [LN("Pass-through charges", "% markup on cost", "B2B", "Advanced", 0.10, 0.25, [A(28), A(36), A(34), H(241)], default=0.20, basis="UNIS template markup (20%)", pct=True)]),
])

# =============================================================== TV / specialty receiving (kept inside Inbound for webform grouping)
SECTIONS[1][1].append(SV("IN-10", "TV / Display Receiving (by screen size)",
    "Receive TVs / monitors (incl. retail returns) priced per unit by screen size.",
    "Per unit received",
    "Specialty line (highest-usage inbound code at UNIS). 98\"+ quoted per request (inconsistent price data).",
    [LN(f"TV receiving {lbl}", "Unit", "B2B", "Core", None, None, [H(123), H(175)], inc=rx) for lbl, rx in TV]
    + [LN("TV outbound handling (per unit)", "Unit", "B2B", "Advanced", None, None, [H(147)])]))

# Codes kept for billing only - never on the customer quote
INTERNAL = {
    "Claims": [A(4), H(198), S(29), "Small Parcel-0006", "DRAYAGE-0002"],
    "Discounts & incentives": ["DISCOUNT-0001", "Gift-0001"],
    "Late fee (contract term)": ["LATE CHARGE-0001"],
    "Security deposit (contract term)": ["SECURITY DEPOSIT-0001"],
    "Generic / misc (re-map where possible)": ["MISCELLANEOUS REVENUE-0001", A(3), H(254)],
}
