# Service catalog spec: consolidates the WMS billing codes into human-readable rate-card services.
# Each service -> Scope row (File2 style) + list of enumerated rate-card lines.
# L(line_item, unit, dimension, option, codes, inc=regex on price-list description, exc=regex, b2b=, d2c=, note=)

MIN = r"minimum|mini ?monthly|min\b"

def L(line, unit, dim, opt, codes, inc=None, exc=MIN, b2b=None, d2c=None, note=None, ratetype="Unit Price"):
    return dict(line=line, unit=unit, dim=dim, opt=opt, codes=codes, inc=inc, exc=exc, b2b=b2b, d2c=d2c, note=note, ratetype=ratetype)

def H(n): return f"HANDLING-{n:04d}"
def S(n): return f"STORAGE INCOME-{n:04d}"
def A(n): return f"ACCESSORIAL-{n:04d}"

SECTIONS = []  # (section title, [services])

def section(title, services): SECTIONS.append((title, services))

def svc(sid, name, applies, activity, trigger, enums, notes, codes, lines):
    return dict(id=sid, name=name, applies=applies, activity=activity, trigger=trigger, enums=enums, notes=notes, codes=codes, lines=lines)

# ---------------------------------------------------------------- INBOUND
OFF_CASE = [H(129), H(130), H(180)]
section("INBOUND HANDLING (RECEIVING)", [
 svc("IN-01", "Container Unload - Floor Loaded (tiered by case count)", "B2B / Both",
     "Container or trailer arrives floor-loaded (loose cartons, hand-stacked). UNIS unloads, palletizes (1 SKU per pallet), and records the inventory in the WMS.",
     "Per container, flat fee set by the case-count band of the container",
     "Unit: Container. Case-count band: 0-500 | 501-1,000 | 1,001-1,500 | 1,501-2,000 | 2,001-2,500 | over 2,500 (top band = base fee + per-case charge for each case over 2,500)",
     "Does NOT include put-away, pallet cost or stretch wrap (bill separately under IN-10, MAT-01). A 'Palletized' load-type variant of this tier table exists in the system; for pre-built pallets use IN-02 instead. Trigger may be set at Offload or 'Billed Upon Receipt' - same price, different system event.",
     OFF_CASE + [H(128), H(127), H(179), H(181)],
     [L("Container Unload - Floor Loaded", "Container", "Case-count band", "0 - 500 cases", OFF_CASE, r"(?<![\d])0 ?- ?(499|500)\b", b2b=570),
      L("Container Unload - Floor Loaded", "Container", "Case-count band", "501 - 1,000 cases", OFF_CASE, r"\b50[01] ?- ?1,?000\b|(?<![\d])1 ?- ?1000\b|(?<![\d])0 ?- ?1000\b", b2b=610),
      L("Container Unload - Floor Loaded", "Container", "Case-count band", "1,001 - 1,500 cases", OFF_CASE, r"\b100[01] ?- ?1,?(499|500)\b|(?<![\d])0 ?- ?1500\b", b2b=640),
      L("Container Unload - Floor Loaded", "Container", "Case-count band", "1,501 - 2,000 cases", OFF_CASE, r"\b150[01] ?- ?2,?000\b"),
      L("Container Unload - Floor Loaded", "Container", "Case-count band", "2,001 - 2,500 cases", OFF_CASE, r"\b(2000|1500) ?- ?2,?500\b", b2b=680),
      L("Container Unload - Floor Loaded", "Container", "Case-count band", "Over 2,500 cases - base fee", OFF_CASE, r"over 2,?500|2500 ?- ?300[01]", b2b=715),
      L("Container Unload - Floor Loaded", "Case", "Case-count band", "Each case over 2,500 (incremental)", [H(127), H(128), H(179)], None, b2b=0.26),
     ]),
 svc("IN-02", "Palletized Receiving (per pallet)", "B2B / Both",
     "Freight arrives on pre-built pallets (LTL or full truckload/container). UNIS unloads each pallet, verifies count/SKU, labels and receives it into the WMS.",
     "Per pallet received; a minimum per truckload/container applies. Alternative: flat per container tiered by pallet count",
     "Unit: Pallet | Container. Pallet type: Single-SKU pallet | Mixed-SKU pallet | Oversize pallet (by footprint). Pallet-count band (container flat): 0-20 | 21-40 | over 40",
     "Price assumes 1 SKU per pallet; mixed pallets that must be broken down also trigger Sort & Segregation (IN-08) or Palletizing (IN-09). Minimum charge per truckload (current template $325).",
     [H(113), H(119), H(121), H(166), H(173), H(159), H(105), H(118), H(171), H(120), H(122), H(172), H(174)],
     [L("Palletized Receiving", "Pallet", "Pallet type", "Single-SKU pallet (standard)", [H(113), H(119), H(121), H(166), H(173), H(159), H(105)], None, b2b=10.5),
      L("Palletized Receiving", "Pallet", "Pallet type", "Oversize / non-standard pallet footprint", [H(118), H(171)], None),
      L("Palletized Receiving", "Truckload / Container", "Minimum", "Minimum charge per truckload / container", [H(113), H(121), H(119)], r"minimum", exc=None, b2b=325),
      L("Palletized Receiving - Container Flat", "Container", "Pallet-count band", "0 - 20 pallets", [H(120), H(172)], r"0 ?- ?20\b"),
      L("Palletized Receiving - Container Flat", "Container", "Pallet-count band", "21 - 40 pallets", [H(120), H(172)], r"20 ?- ?40\b"),
      L("Palletized Receiving - Container Flat", "Container", "Pallet-count band", "Over 40 pallets", [H(120), H(172), H(122), H(174)], r"over (40|60|90)|0 ?- ?90"),
     ]),
 svc("IN-03", "Container / Truckload Unload - Flat Rate", "B2B",
     "Unload a full container, trailer or truckload for one flat fee regardless of case count, priced by equipment size. Also used for a flat per-receipt receiving fee.",
     "Per container / per load / per receipt",
     "Unit: Container | Load | Receipt. Container size: 20' | 40' | 40' HC | 45' / 48' / 53' trailer | Any size",
     "Use when case count is unpredictable or product is irregular (panels, steel, appliances). Includes CHEP pallet truckload offloading.",
     [H(126), H(178), H(112), H(164), H(252), H(188), H(125), H(177)],
     [L("Flat Unload", "Container", "Container size", "20' container", [H(126), H(178)], r"20'"),
      L("Flat Unload", "Container", "Container size", "40' / 40' HC container", [H(126), H(178)], r"40'"),
      L("Flat Unload", "Container", "Container size", "Any size (all containers)", [H(126), H(178)], r"all container", exc=MIN + r"|20'|40'"),
      L("Flat Unload", "Load", "Equipment", "Per truckload / trailer", [H(112), H(164), H(252), H(188)], None),
      L("Flat Unload", "Receipt", "Equipment", "Per receipt (any equipment)", [H(125), H(177)], None),
     ]),
 svc("IN-04", "Loose-Unit Receiving (per carton / piece / volume / weight)", "D2C / Both",
     "Receive loose freight (small parcel, LTL, irregular) and bill on the quantity actually received rather than per container.",
     "Per unit received - unit chosen at quote time; optional first-unit / additional-unit split",
     "Unit: Carton | Piece (each) | Inner pack | Cubic foot | Cubic meter | Pound | US ton / metric ton | Rail car. Unit sequence: First unit | Each additional unit",
     "Pick ONE unit basis per client. Legacy generic 'Handling In' per-unit codes also map here.",
     [H(107), H(161), H(104), H(158), H(114), H(167), H(106), H(160), H(111), H(108), H(162), H(109), H(163), H(115), H(168), H(117), H(170), H(165), H(116), H(169), H(195)],
     [L("Loose-Unit Receiving", "Carton", "Unit", "Per carton", [H(107), H(161), H(104), H(158)], None),
      L("Loose-Unit Receiving", "Piece", "Unit", "Per piece / each", [H(114), H(167), H(106), H(160), H(195)], None),
      L("Loose-Unit Receiving", "Inner pack", "Unit", "Per inner pack", [H(111)], None),
      L("Loose-Unit Receiving", "Cubic foot", "Unit", "Per cubic foot", [H(108), H(162)], None),
      L("Loose-Unit Receiving", "Cubic meter", "Unit", "Per cubic meter", [H(109), H(163)], None),
      L("Loose-Unit Receiving", "Weight", "Unit", "Per pound / ton", [H(115), H(168), H(117), H(170), H(165)], None),
      L("Loose-Unit Receiving", "Rail car", "Unit", "Per rail car", [H(116), H(169)], None),
     ]),
 svc("IN-05", "Receiving by Item Type (TV / display size)", "B2B",
     "Consumer-electronics receiving priced per unit according to the screen size of the TV / monitor received (covers retail returns as well as regular receipts).",
     "Per unit received, rate set by screen-size band",
     'Unit: Each. Screen size: up to 32" | 37"-43" | 46"-50" | 55"-60" | 65" | 70"-75" | 80"-86" | 98" and larger',
     "Highest-usage inbound code in the system (221 customers). Pairs with TV storage (ST-04) and TV loading (OB-11).",
     [H(123), H(175)],
     [L("Receiving by TV Size", "Each", "Screen size", 'Up to 32"', [H(123), H(175)], r'\b(19|20|22|23|24|25|26|27|28|29|32)"'),
      L("Receiving by TV Size", "Each", "Screen size", '37" - 43"', [H(123), H(175)], r'\b(37|39|40|42|43)"'),
      L("Receiving by TV Size", "Each", "Screen size", '46" - 50"', [H(123), H(175)], r'\b(46|47|48|49|50)"'),
      L("Receiving by TV Size", "Each", "Screen size", '55" - 60"', [H(123), H(175)], r'\b(55|58|60)"'),
      L("Receiving by TV Size", "Each", "Screen size", '65"', [H(123), H(175)], r'\b65"'),
      L("Receiving by TV Size", "Each", "Screen size", '70" - 75"', [H(123), H(175)], r'\b(70|71|75)"'),
      L("Receiving by TV Size", "Each", "Screen size", '80" - 86"', [H(123), H(175)], r'\b(80|82|85|86)"'),
      L("Receiving by TV Size", "Each", "Screen size", '98" and larger', [H(123), H(175)], r'\b(98|100|110|120)"'),
     ]),
 svc("IN-06", "Hourly Receiving (labor-based unload & stow)", "D2C / Both",
     "Unload and stow inbound freight billed on actual labor time - typical for small-parcel, LCL and LTL receipts where piece counts vary.",
     "Per labor hour (15-min increments); a minimum charge per receipt may apply",
     "Unit: Hour. Ship method: Small parcel | LTL | LCL | Floor-loaded / Palletized. Minimum per receipt",
     'D2C template "Inbound and stow all products" is this line.',
     [H(124), H(176)],
     [L("Hourly Receiving", "Hour", "Ship method", "Small parcel", [H(124), H(176)], r"small parcel", d2c=45),
      L("Hourly Receiving", "Hour", "Ship method", "LTL / LCL", [H(124), H(176)], r"\bLTL\b|\bLCL\b"),
      L("Hourly Receiving", "Hour", "Ship method", "Any / unspecified", [H(124), H(176)], r"^Rate by Hour$"),
      L("Hourly Receiving", "Hour", "Minimum", "Minimum charge (hours-equivalent)", [H(124), H(176)], r"minimum", exc=None),
     ]),
 svc("IN-07", "Shotgun-Loaded Surcharge", "B2B",
     'Extra labor to unload cartons that were "shotgunned" (loosely thrown, not stacked) into the container.',
     "Per carton (added on top of the container unload fee)",
     "Unit: Carton | Piece | Pallet",
     "Always IN ADDITION to IN-01 / IN-03.",
     [H(33), H(34), H(35)],
     [L("Shotgun-Loaded Surcharge", "Carton", "Unit", "Per carton", [H(33), H(34), H(35)], None, b2b=0.35)]),
 svc("IN-08", "Inbound Sort & Segregation", "B2B",
     "Sort and separate cartons when a receipt contains more SKUs than the standard allowance (template: more than 5 commingled SKUs).",
     "Per carton (or per SKU / piece) above the SKU threshold",
     "Unit: Carton | Piece | SKU | Receipt | Load. Threshold: SKU count per receipt (default > 5)",
     "Only triggers above the SKU threshold agreed in the quote.",
     [H(28), H(29), H(30), H(31), H(32)],
     [L("Inbound Sort & Segregation", "Carton", "Unit", "Per carton", [H(29)], None, b2b=0.25),
      L("Inbound Sort & Segregation", "SKU", "Unit", "Per SKU over threshold", [H(28)], None),
      L("Inbound Sort & Segregation", "Piece", "Unit", "Per piece", [H(30)], None)]),
 svc("IN-09", "Inbound Palletizing / Re-Palletizing", "B2B",
     "Build loose cartons onto pallets, or rebuild/re-configure inbound pallets to warehouse standard (pallet-to-pallet transfer).",
     "Per pallet built (or per carton / per container)",
     "Unit: Pallet | Carton | Container. Type: Loose carton to pallet | Pallet to pallet (rebuild)",
     "Normally included in IN-01 floor-loaded unload; bill only when palletizing is not already part of the unload fee.",
     [H(81), H(82), H(83)],
     [L("Inbound Palletizing", "Pallet", "Type", "Loose carton to pallet / pallet rebuild", [H(81), H(82), H(83)], None)]),
 svc("IN-10", "Put Away to Inventory", "B2B / Both",
     "Move a received pallet (or carton) from the dock to its assigned storage location and confirm the put-away in the WMS.",
     "Per pallet (or carton / piece)",
     "Unit: Pallet | Carton | Piece",
     "Applies after any inbound method (IN-01 ... IN-06).",
     [H(53), H(54), H(55)],
     [L("Put Away", "Pallet", "Unit", "Per pallet", [H(53), H(54), H(55)], None, b2b=4.5)]),
 svc("IN-11", "Receipt Processing & Manual Receipt Entry", "Both",
     "Admin processing of each inbound receipt; manual entry applies when a CSR keys the receipt/ASN into the WMS because it was not sent electronically.",
     "Per receipt / per load / per receipt line",
     "Type: Receipt processing (per receipt or load) | Manual receipt entry (per receipt) | Manual receipt entry (per receipt line)",
     "Electronic (EDI/FTP) receipts bill under IT-05 instead of manual entry.",
     [H(41), H(42), H(51), H(52)],
     [L("Receipt Processing", "Receipt", "Type", "Receipt processing (per receipt / load)", [H(41), H(42)], None),
      L("Manual Receipt Entry", "Receipt", "Type", "Manual entry - per receipt", [H(51)], None),
      L("Manual Receipt Entry", "Receipt line", "Type", "Manual entry - per receipt line", [H(52)], None)]),
 svc("IN-12", "No ASN / Packing List", "Both",
     "Client fails to provide an ASN or packing list in advance (template: 5 days before vessel arrival).",
     "Per receipt",
     "Unit: Receipt",
     "Compliance charge, not a handling charge - billed regardless of receipt size.",
     [A(18)],
     [L("No ASN / Packing List", "Receipt", "-", "Per receipt", [A(18)], None, b2b=50)]),
 svc("IN-13", "OSD / Damage Documentation & Reporting", "Both",
     "Document overage, shortage and damage (OSD) outside the normal receiving scope - photos, counts and a written report to the client.",
     "Per hour (15-min increments)",
     "Unit: Hour",
     "Routine damage noted during standard receiving is included in the base receiving rate.",
     [H(219)],
     [L("OSD / Damage Reporting", "Hour", "-", "Per hour", [H(219)], None, b2b=50)]),
])

# ---------------------------------------------------------------- TRANSLOAD
TL_CASE = [H(26), H(27)]
section("TRANSLOAD & CROSS-DOCK", [
 svc("TL-01", "Transload (container to domestic trailer)", "B2B",
     "Unload an ocean container or rail car and reload the product into one or more domestic trailers without putting it into storage.",
     "Per container (by size, case-count band or pallet-count band), or per pallet / carton / unit",
     "Unit: Container | Pallet | Carton | Load | Receipt | Piece | Cubic ft / m | Weight | Rail car | Hour. Container size: 20' | 40' / 40' HC | 45' / 53'. Case-count band: 0-500 | 501-1,000 | 1,001-2,000 | 2,001-3,000 | over 3,000. Pallet-count band: 0-20 | 21-40",
     "One service with many unit options - quote ONE pricing basis per lane. Load type (floor-loaded / palletized / slip-sheet) can carry different rates.",
     [H(n) for n in range(3, 28) if n not in ()],
     [L("Transload", "Container", "Container size", "20' container", [H(23)], r"20'"),
      L("Transload", "Container", "Container size", "40' / 40' HC / 45' / 53'", [H(23)], r"40'|45'|53'"),
      L("Transload", "Container", "Container size", "Any size", [H(23)], None),
      L("Transload", "Container", "Case-count band", "0 - 1,000 cases", TL_CASE, r"0 ?- ?500|500 ?- ?1000"),
      L("Transload", "Container", "Case-count band", "1,001 - 3,000 cases", TL_CASE, r"1000 ?- ?(1500|2000)|2000 ?- ?3000|1500 ?- ?2500"),
      L("Transload", "Container", "Case-count band", "Over 3,000 cases", TL_CASE, r"over 3000|3000 ?- ?4000"),
      L("Transload", "Container", "Pallet-count band", "Per container by pallet count", [H(17), H(19)], None),
      L("Transload", "Pallet", "Unit", "Per pallet", [H(11), H(16), H(18), H(4)], None),
      L("Transload", "Carton", "Unit", "Per carton", [H(6), H(24), H(25), H(3)], None),
      L("Transload", "Load", "Unit", "Per load (floor-loaded)", [H(9)], None),
      L("Transload", "Receipt", "Unit", "Per receipt", [H(22), H(15)], None),
      L("Transload", "Piece", "Unit", "Per piece / unit", [H(12), H(5), H(20)], None),
      L("Transload", "Volume", "Unit", "Per cubic foot / cubic meter", [H(7), H(8)], None),
      L("Transload", "Hour", "Unit", "Per labor hour", [H(21)], None)]),
 svc("XD-01", "Cross-Dock (flow-through)", "B2B",
     "Receive pallets and ship them out on another truck the same day / within the cross-dock window without put-away to storage.",
     "Per pallet",
     "Unit: Pallet",
     "No storage charge if shipped within the cross-dock window; otherwise storage applies.",
     [H(157)],
     [L("Cross-Dock", "Pallet", "-", "Per pallet", [H(157)], None)]),
])

# ---------------------------------------------------------------- OUTBOUND ORDERS
OP = [H(93)]
section("OUTBOUND - ORDER HANDLING", [
 svc("OB-01", "Order Processing", "Both",
     "Process an outbound order: release to the floor, generate BOL / packing list (B2B) or shipping label (D2C), and confirm shipment in the WMS.",
     "Per order (alternatives: per load, order line, carton or piece)",
     "Order profile: B2B Truckload / LTL | B2B Small parcel | D2C / Drop-ship. Unit: Order | Load | Order line | Carton | Piece. D2C option: package weight band",
     "An order is billed as Order Processing + Picking (OB-06..09) + any accessorials actually used - never as one flat 'ship the order' fee.",
     [H(93), H(89), H(90), H(91), H(92), H(94)],
     [L("Order Processing", "Order", "Order profile", "B2B - Truckload / LTL (incl. BOL & packing list)", OP, r"truckload|\bLTL\b", b2b=22, d2c=22),
      L("Order Processing", "Order", "Order profile", "B2B - Small parcel", OP, r"small parcel"),
      L("Order Processing", "Order", "Order profile", "Regular order - ship method not specified", OP, r"regular order", exc=MIN + r"|truckload|\bLTL\b|small parcel|dropship"),
      L("Order Processing", "Order", "Order profile", "D2C / Drop-ship order (no packing list)", OP + [H(89)], r"drop ?ship|b2c", b2b=2, d2c=2),
      L("Order Processing", "Order", "D2C package weight", "D2C order, 5 - 10 lbs", [H(89)], r"over|5 ?- ?10", d2c=3),
      L("Order Processing", "Load", "Unit", "Per load / shipment", [H(92)], None),
      L("Order Processing", "Carton", "Unit", "Per carton shipped", [H(90)], None)]),
 svc("OB-02", "Manual Order Entry", "Both",
     "CSR manually keys an order into the system on the client's behalf (order not received via EDI / API / portal).",
     "Per order (or per order line)",
     "Unit: Order | Order line",
     "Not charged for orders received electronically (see IT-05).",
     [H(96), H(97)],
     [L("Manual Order Entry", "Order", "Unit", "Per order", [H(96)], None, b2b=15, d2c=15),
      L("Manual Order Entry", "Order line", "Unit", "Per order line", [H(97)], None)]),
 svc("OB-03", "Rush Processing (same-day)", "Both",
     "Order received after the daily cut-off (template: 11:00 a.m. local warehouse time) and processed the same day; also rush receipts.",
     "Per order / per receipt",
     "Direction: Outbound order | Inbound receipt",
     None,
     [H(88), H(40)],
     [L("Rush Processing", "Order", "Direction", "Rush outbound order", [H(88)], None, b2b=50, d2c=50),
      L("Rush Processing", "Receipt", "Direction", "Rush inbound receipt", [H(40)], None)]),
 svc("OB-04", "Canceled Order Fee", "Both",
     "Order canceled by the client after it has been released to the warehouse.",
     "Per order; after picking also add return-to-stock labor at the hourly rate",
     "Timing: Canceled before picking | Canceled after picking",
     None,
     [A(1), A(2), A(7)],
     [L("Canceled Order", "Order", "Timing", "Canceled before picking", [A(1), A(7)], None),
      L("Canceled Order", "Order", "Timing", "Canceled after picking (+ return-to-stock hourly)", [A(2)], None, b2b=10, d2c=10)]),
 svc("OB-05", "Missed Appointment Fee", "B2B",
     "Carrier/driver misses a scheduled dock appointment that was not cancelled in time (template: by 11:00 a.m. the day before).",
     "Per occurrence (per load / receipt / order)",
     "Direction: Inbound (receipt/load) | Outbound (order)",
     None,
     [H(43), H(44), H(95)],
     [L("Missed Appointment", "Occurrence", "Direction", "Inbound - receipt / load", [H(43), H(44)], None),
      L("Missed Appointment", "Occurrence", "Direction", "Outbound - order", [H(95)], None, b2b=50, d2c=50)]),
])

# ---------------------------------------------------------------- PICKING
section("OUTBOUND - PICKING", [
 svc("OB-06", "Pallet Pick (full pallet, single SKU)", "B2B",
     "Pick an intact full pallet of a single SKU and stage it for shipment, with pallet label.",
     "Per pallet (alternatives: tiered by pallets per order, or flat per order)",
     "Unit: Pallet | Order. Pallets-per-order band: 1-12 | 13-30 | over 30. Minimum per order",
     "Bills ONLY when an intact pallet ships with no breakdown. If the pallet is broken down / relabeled / re-palletized, bill Pallet Pick + Case Pick + labor (see Methodology).",
     [H(67), H(75), H(77), H(76), H(60)],
     [L("Pallet Pick", "Pallet", "Unit", "Per full pallet", [H(67), H(77), H(60)], None, b2b=10.5),
      L("Pallet Pick", "Pallet", "Pallets-per-order band", "Tiered by pallets per order", [H(75)], None),
      L("Pallet Pick", "Order", "Unit", "Flat per order (by pallet count)", [H(76)], None),
      L("Pallet Pick", "Order", "Minimum", "Minimum per order", [H(67)], r"minimum", exc=None)]),
 svc("OB-07", "Case / Carton Pick", "B2B / Both",
     "Pick full cartons (cases) for a wholesale / retail order.",
     "Per carton; rate may vary by carton weight band; minimum per order",
     "Unit: Carton. Carton weight: 0-30 lbs | 31-60 lbs | over 60 lbs. Sequence: First carton | Each additional carton. Minimum per order",
     "Standard rate assumes cartons of 30 lbs or less.",
     [H(63), H(72), H(57)],
     [L("Case Pick", "Carton", "Carton weight", "0 - 30 lbs (standard)", [H(63), H(72)], r"0 ?- ?30 lbs|^rate by unit$|regular order", exc=MIN + r"drop ?ship", b2b=1.05, d2c=1.65),
      L("Case Pick", "Carton", "Carton weight", "Up to 60 lbs", [H(72)], r"0 ?- ?60 lbs"),
      L("Case Pick", "Carton", "Carton weight", "Over 60 lbs", [H(72)], r"over 60"),
      L("Case Pick", "Carton", "Sequence", "First carton / each additional (split rate)", [H(57)], None),
      L("Case Pick", "Order", "Minimum", "Minimum per order", [H(63)], r"minimum", exc=None, d2c=20)]),
 svc("OB-08", "Each / Inner-Pack Pick (piece pick)", "D2C / Both",
     "Pick individual units (eaches) or inner packs out of a case - typical for D2C / e-commerce and small B2B orders.",
     "Per each (or per inner pack); optional first-unit / additional-unit split and weight bands",
     "Unit: Each | Inner pack | Order line | Order. Order type: D2C / Drop-ship | B2B regular. Sequence: First unit | Each additional. Weight band (per unit or per order)",
     None,
     [H(69), H(64), H(68), H(73), H(74), H(58), H(59), H(61), H(62), H(56), H(65), H(66)],
     [L("Each Pick", "Each", "Order type", "D2C / Drop-ship", [H(69), H(64), H(68)], r"drop ?ship|b2c", b2b=0.5, d2c=0.5),
      L("Each Pick", "Each", "Order type", "B2B / regular order", [H(69), H(68)], r"regular|b2b|^rate by unit$", exc=MIN + r"|drop ?ship|b2c"),
      L("Each Pick", "Inner pack", "Unit", "Per inner pack", [H(64)], None, exc=MIN + r"|drop ?ship|b2c"),
      L("Each Pick", "Each", "Weight band", "Priced by unit weight band", [H(73), H(74)], None),
      L("Each Pick", "Each", "Sequence", "First unit / each additional (split rate)", [H(58), H(59), H(61), H(62), H(56)], None),
      L("Each Pick", "Order line", "Unit", "Per order line", [H(65)], None)]),
 svc("OB-09", "Bulk Pick by Weight / Volume", "B2B",
     "Pick bulk / irregular product billed on weight or cube instead of unit count.",
     "Per pound / ton / cubic foot / cubic meter",
     "Unit: Pound | US ton | Metric ton | Cubic foot | Cubic meter",
     "Rarely used; quote only for bulk commodities.",
     [H(70), H(71), H(78), H(79), H(80)],
     [L("Bulk Pick", "Weight", "Unit", "Per ton", [H(71), H(80)], None),
      L("Bulk Pick", "Volume", "Unit", "Per cubic foot / cubic meter", [H(78), H(79)], None)]),
])

# ---------------------------------------------------------------- PACK / LOAD / SHIP
section("OUTBOUND - PACKING, LOADING & SHIPPING", [
 svc("OB-10", "Packing", "D2C / Both",
     "Pack picked items into a shipping carton / mailer for small-parcel (D2C) or pack out a regular B2B order.",
     "Per order or per carton packed",
     "Type: Small-parcel pack | Regular (B2B) pack. Unit: Order | Carton",
     "Packaging materials bill separately (MAT-02) unless included in the quote.",
     [H(84), H(85), H(86), H(87)],
     [L("Packing", "Order", "Type", "Small-parcel pack - per order", [H(84)], None),
      L("Packing", "Carton", "Type", "Small-parcel pack - per carton", [H(85)], None),
      L("Packing", "Carton", "Type", "Regular (B2B) pack - per carton", [H(87)], None)]),
 svc("OB-11", "Outbound Loading", "B2B",
     "Load outbound freight onto the carrier's trailer / container (floor-loaded or palletized).",
     "Per pallet / carton / piece loaded, or flat per container / load / order",
     "Unit: Pallet | Carton | Piece | Container | Load | Order | Weight / Volume | Each (TV size). Container size: 20' / 40' / 45' / 53'. Carton-volume band per period: 0-500 | 501-750 | over 750",
     "Floor-loading a container outbound is the most common use. Legacy generic 'Handling Out' per-unit code maps here.",
     [H(n) for n in range(131, 155) if n not in (155,)] + [H(197)],
     [L("Outbound Loading", "Pallet", "Unit", "Per pallet", [H(142), H(136), H(146)], None),
      L("Outbound Loading", "Carton", "Unit", "Per carton (floor-loaded)", [H(138), H(133), H(131), H(135), H(152)], None),
      L("Outbound Loading", "Piece", "Unit", "Per piece", [H(143), H(132), H(134), H(137)], None),
      L("Outbound Loading", "Container", "Container size", "Flat per container", [H(151), H(153)], None),
      L("Outbound Loading", "Load", "Unit", "Flat per load / order", [H(148), H(149), H(150), H(154)], None),
      L("Outbound Loading", "Each", "Screen size", "Per TV by screen size", [H(147)], None)]),
 svc("OB-12", "Shipping Label - Print & Apply", "Both",
     "Print and apply a UCC-128 / carrier shipping label, or apply a label supplied by the client.",
     "Per label",
     "Type: UNIS prints & applies | Client-provided label applied",
     None,
     [H(155), H(156)],
     [L("Shipping Label", "Label", "Type", "UNIS prints & applies (UCC-128 / carrier)", [H(155)], None, b2b=0.6, d2c=0.4),
      L("Shipping Label", "Label", "Type", "Apply client-provided label", [H(156)], None)]),
 svc("OB-13", "Routing to Retailers", "B2B",
     "Retailer-specific routing request / paperwork (routing guide compliance, carrier booking via retailer portal).",
     "Per bill of lading (order)",
     "Unit: BOL / Order",
     None,
     [H(239)],
     [L("Routing to Retailers", "BOL", "-", "Per bill of lading", [H(239)], None, b2b=12.5, d2c=12.5)]),
 svc("OB-14", "Manual Address Correction", "D2C",
     "Correct or update a ship-to address after the order was received.",
     "Per occurrence",
     "Unit: Occurrence",
     None,
     [A(37)],
     [L("Address Correction", "Occurrence", "-", "Per correction", [A(37)], None, d2c=2.5)]),
 svc("OB-15", "Freight, Small Parcel & Postage", "Both",
     "Transportation charges passed through or billed by UNIS: small-parcel postage, FTL/LTL freight, and a handling fee when the client uses its own (3rd-party) postage account.",
     "Per tracking number / order / container, or cost-plus",
     "Type: Small-parcel freight (per tracking #) | FTL / LTL freight | Transportation per container | 3rd-party postage handling (per order)",
     "Freight itself is usually billed at cost-plus (template: postage cost + 20%).",
     ["Small Parcel-0003", "Small Parcel-0004", "Small Parcel-0005", "TRANSPORTATION-0002", H(182)],
     [L("3rd-Party Postage Handling", "Order", "Type", "Client uses own postage account", [H(182)], None, d2c=0.75),
      L("Small-Parcel Freight", "Tracking #", "Type", "Per tracking number (plus postage)", ["Small Parcel-0005"], None),
      L("Transportation", "Container", "Type", "Per container", ["Small Parcel-0003"], None)]),
])

# ---------------------------------------------------------------- VAS
section("VALUE-ADDED SERVICES (VAS)", [
 svc("VA-01", "Packaging Add-Ons (D2C)", "D2C",
     "Optional packaging steps on e-commerce orders: overbox, dunnage/void fill, repack, package prep; (template also lists branded packaging, fragile wrap, inserts).",
     "Per box / per order / per each, or hourly for package prep",
     "Add-on: Overbox | Dunnage | Repack | Package prep (hourly) | Branded packaging* | Fragile / tissue wrap* | Insert / flier / sticker*  (*no billing code yet)",
     "Material cost excluded unless stated. Minimum monthly volumes may apply (D2C template: branded packaging min 2,000 orders/month).",
     ["ACC-0003", "OVERBOX", "DUNNAGE", H(233), H(226)],
     [L("Packaging Add-On", "Box", "Add-on", "Overbox goods (corrugate)", ["ACC-0003", "OVERBOX"], None, d2c=0.5),
      L("Packaging Add-On", "Each", "Add-on", "Dunnage / void fill", ["DUNNAGE"], None, d2c=0.5),
      L("Packaging Add-On", "Each", "Add-on", "Repack", [H(233)], None),
      L("Packaging Add-On", "Order", "Add-on", "Branded packaging (incl. tape) - NO CODE", [], None, d2c=0.35),
      L("Packaging Add-On", "Each", "Add-on", "Fragile / tissue wrap - NO CODE", [], None, d2c=0.5),
      L("Packaging Add-On", "Each", "Add-on", "Insert / flier / tag / sticker - NO CODE", [], None, d2c=0.15)]),
 svc("VA-02", "Product Labeling & Relabeling", "Both",
     "Apply, replace or remove labels on product or cartons: item / SKU labels, Amazon FNSKU labels, serial-number labels, relabel / re-mark master cartons, SKU conversion.",
     "Per label / unit / carton, or per hour for large label projects",
     "Label type: Item / SKU label | Amazon (FNSKU) label | Amazon SKU conversion | Customized label | Serial-number label | Relabel / label removal | Re-mark master carton | Labeling labor (hourly)",
     "Shipping labels are OB-12, not this line.",
     [H(210), H(211), H(184), "ACC-0002", "ACC-0004", "RELABELING", H(232), H(209), H(212)],
     [L("Product Labeling", "Label", "Label type", "Amazon (FNSKU) label", [H(184)], None),
      L("Product Labeling", "Unit", "Label type", "Amazon SKU conversion", ["ACC-0004"], None),
      L("Product Labeling", "Unit", "Label type", "Customized label", ["ACC-0002"], None),
      L("Product Labeling", "Hour", "Label type", "Labeling labor (hourly)", [H(212)], None)]),
 svc("VA-03", "Kitting & Assembly", "Both",
     "Assemble components into a kit or finished SKU per client work order (incl. pick of components and put-away of the finished kit).",
     "Per kit (each) or per carton with work order; complex assembly per hour",
     "Unit: Each (kit) | Carton (with work order) | Hour (assembly / assembly pick / assembly put-away)",
     "Always IN ADDITION to the underlying pick / storage charges. Confirm quantity and time estimate before work starts.",
     [H(208), H(207), H(187), H(185), H(186)],
     [L("Kitting", "Each", "Unit", "Per kit / each", [H(208)], None),
      L("Kitting", "Carton", "Unit", "Per carton with work order", [H(207)], None),
      L("Assembly", "Hour", "Unit", "Assembly labor per hour", [H(187), H(185), H(186)], None)]),
 svc("VA-04", "Serial Number Tracking", "Both",
     "Scan and record serial numbers / barcodes at receiving or shipping.",
     "Per serial number scanned",
     "Unit: Scan",
     None,
     [H(243)],
     [L("Serial Number Tracking", "Scan", "-", "Per serial number", [H(243)], None, b2b=1.25, d2c=1.25)]),
 svc("VA-05", "Photos", "Both",
     "Photograph product, cartons or pallets on request (condition reports, returns, compliance).",
     "Per photo / per item",
     "Unit: Photo",
     "Return-program photos are included in the standard return fee (RT-01) unless extra photos are requested.",
     [A(27), "RMS-005"],
     [L("Photos", "Photo", "-", "Per photo", [A(27), "RMS-005"], None)]),
])

# ---------------------------------------------------------------- STORAGE
PAL_R = [S(4), S(11), S(9)]
PAL_I = [S(17), S(24), S(22)]
section("STORAGE", [
 svc("ST-01", "Pallet Storage (per pallet position)", "Both",
     "Store product on pallets in a pallet position (floor bulk-stacked or racked). Standard is 1 SKU per position, footprint no greater than 40x48x58 in.",
     "Per pallet position. Initial storage billed at receipt; recurring storage billed on the 1st of each month (or weekly/daily per contract)",
     "Billing event: Initial (at receipt; full-month or half-month) | Recurring (monthly / weekly / daily). Stack height: 1-high | 2-high | 3-high | 4-high+ | Rack. Pallet size: Standard 40x48 | Oversize (priced by footprint)",
     "A partial pallet occupying a full location bills as one position. Aged-inventory surcharges (days-range conditions) apply separately. Monthly minimum: see ST-07.",
     PAL_R + PAL_I,
     [L("Pallet Storage", "Pallet / month", "Billing event", "Recurring - monthly", [S(4)], r"monthly", b2b=22, d2c=22),
      L("Pallet Storage", "Pallet", "Billing event", "Initial - at receipt", [S(17)], None, b2b=22),
      L("Pallet Storage", "Pallet / week", "Billing event", "Recurring - weekly", [S(4)], r"weekly"),
      L("Pallet Storage", "Pallet / month", "Stack height", "1-high", [S(11), S(24)], r"\b1 high"),
      L("Pallet Storage", "Pallet / month", "Stack height", "2-high", [S(11), S(24)], r"\b2 high"),
      L("Pallet Storage", "Pallet / month", "Stack height", "3-high", [S(11), S(24)], r"\b3 high"),
      L("Pallet Storage", "Pallet / month", "Stack height", "4-high and above", [S(11), S(24)], r"\b([4-9]|10) high"),
      L("Pallet Storage", "Pallet / month", "Stack height", "Rack position", [S(11), S(24)], r"rack"),
      L("Pallet Storage", "Pallet / month", "Pallet size", "Oversize pallet (by footprint)", [S(9), S(22)], None)]),
 svc("ST-02", "Bin / Shelf / Rack Storage (by location type)", "D2C",
     "Store small or slow-moving SKUs in shelving bins or rack locations instead of full pallet positions - typical for e-commerce.",
     "Per location per month (billed at receipt and on the 1st of the month)",
     "Location type: Small bin | Large bin | Rack / shelf | Pallet position. Period: Monthly | Weekly | Daily",
     "Single SKU per bin. Price list data does not record the location type per row - the reference median mixes types; use the D2C template values per type.",
     [S(13), S(26)],
     [L("Location Storage", "Location / month", "Location type", "Small bin", [], None, d2c=4, note="Code exists (STORAGE INCOME-0013/0026) but price lists do not record the location type - use template rate"),
      L("Location Storage", "Location / month", "Location type", "Large bin", [], None, d2c=8, note="Code exists (STORAGE INCOME-0013/0026) but price lists do not record the location type - use template rate"),
      L("Location Storage", "Location / month", "Location type", "Pallet position / mixed types (system median)", [S(13), S(26)], r"monthly", d2c=22)]),
 svc("ST-03", "Unit Storage (per carton / piece)", "Both",
     "Storage billed per carton or per piece on hand instead of per location.",
     "Per carton / piece per period",
     "Unit: Carton | Piece. Billing event: Initial | Recurring",
     None,
     [S(5), S(6), S(18), S(19)],
     [L("Unit Storage", "Carton", "Unit", "Per carton", [S(5), S(18)], None)]),
 svc("ST-04", "TV / Display Storage (by screen size)", "B2B",
     "Store TVs / monitors, billed per unit according to screen size.",
     "Per unit per month",
     'Screen size: up to 32" | 37"-43" | 46"-50" | 55"-60" | 65" | 70"-75" | 80"-86" | 98"+. Days range: standard | aged (over 60 days). Billing event: Initial | Recurring',
     "Second-highest-usage storage code (146 customers).",
     [S(10), S(23)],
     [L("TV Storage", "Each / month", "Screen size", 'Up to 32"', [S(10), S(23)], r'\b(19|20|22|23|24|25|26|27|28|29|32)"'),
      L("TV Storage", "Each / month", "Screen size", '37" - 43"', [S(10), S(23)], r'\b(37|39|40|42|43)"'),
      L("TV Storage", "Each / month", "Screen size", '46" - 50"', [S(10), S(23)], r'\b(46|47|48|49|50)"'),
      L("TV Storage", "Each / month", "Screen size", '55" - 60"', [S(10), S(23)], r'\b(55|58|60)"'),
      L("TV Storage", "Each / month", "Screen size", '65"', [S(10), S(23)], r'\b65"'),
      L("TV Storage", "Each / month", "Screen size", '70" - 75"', [S(10), S(23)], r'\b(70|71|75)"'),
      L("TV Storage", "Each / month", "Screen size", '80" - 86"', [S(10), S(23)], r'\b(80|82|85|86)"'),
      L("TV Storage", "Each / month", "Screen size", '98" and larger', [S(10), S(23)], r'\b(98|100|110|120)"')]),
 svc("ST-05", "Dedicated Space (per square foot)", "B2B",
     "Rent a dedicated floor area (by location square footage) or bill on the footprint of the items stored; includes space rental / sublease arrangements.",
     "Per square foot per month (weekly / quarterly also supported); monthly minimum usual",
     "Basis: Location (dedicated area) sq ft | Item footprint sq ft. Period: Monthly | Weekly | Quarterly",
     "Almost always paired with a monthly minimum (ST-07).",
     [S(7), S(8), S(20), S(21), S(28), "Sublease Revenue-0001"],
     [L("Dedicated Space", "Sq ft / month", "Basis", "Location square footage", [S(8), S(21)], r"monthly|square", exc=MIN),
      L("Dedicated Space", "Sq ft / month", "Basis", "Item footprint square footage", [S(7), S(20)], None)]),
 svc("ST-06", "Volume / Weight Storage", "B2B",
     "Storage billed on cube (cu ft / cbm) or weight on hand.",
     "Per cubic foot / cubic meter / weight unit per period",
     "Unit: Cubic foot | Cubic meter | Weight (lb / US ton / metric ton). Days range: 0-180 | over 180 days",
     None,
     [S(1), S(2), S(3), S(14), S(15), S(16)],
     [L("Volume Storage", "Cubic foot", "Unit", "Per cubic foot", [S(2), S(15)], None),
      L("Volume Storage", "Cubic meter", "Unit", "Per cubic meter", [S(3), S(16)], None),
      L("Weight Storage", "Weight", "Unit", "Per weight unit", [S(1), S(14)], None)]),
 svc("ST-07", "Monthly Storage Minimum", "Both",
     "Minimum monthly storage commitment billed if actual storage charges fall below it.",
     "Flat per month",
     "Basis: pallet storage | location storage | square-foot storage",
     "Not a separate billing code - configured as a 'Minimum' condition on ST-01 / ST-02 / ST-05. Template value $15,000/month.",
     [],
     [L("Monthly Storage Minimum", "Month", "Basis", "Pallet storage minimum", [S(4)], r"minimum", exc=None, b2b=15000),
      L("Monthly Storage Minimum", "Month", "Basis", "Square-foot storage minimum", [S(8)], r"minimum", exc=None)]),
])

# ---------------------------------------------------------------- YARD
section("YARD & CONTAINER SERVICES", [
 svc("YD-01", "Yard / Container Storage", "B2B",
     "Store a loaded or empty container / trailer in the UNIS yard (incl. outside-carrier containers not pulled on time, and container layover).",
     "Per container per day (monthly/weekly also supported)",
     "Type: Yard storage | Container layover | Container storage (monthly/weekly). Free time per contract (template: outside carriers have 24 hours after empty)",
     None,
     ["YARD-0001", "YARD-0002", S(12), S(25), S(27)],
     [L("Yard Storage", "Container / day", "Type", "Yard storage", ["YARD-0001", "YARD-0002"], None, b2b=35),
      L("Yard Storage", "Container / day", "Type", "Container layover", [S(27)], None)]),
 svc("YD-02", "Yard Hostler (shuttle)", "B2B",
     "Move trailers / containers within the yard or between the yard and the dock with a yard truck.",
     "Per move (weekday) / per hour (weekend)",
     "Day: Weekday | Weekend",
     None,
     [H(250), H(251)],
     [L("Yard Hostler", "Move", "Day", "Weekday", [H(250)], None),
      L("Yard Hostler", "Hour", "Day", "Weekend", [H(251)], None)]),
 svc("YD-03", "Outside Carrier Management", "B2B",
     "Fee per container when inbound drayage is handled by an outside carrier instead of UNIS Transportation (scheduling, gate, paperwork).",
     "Per container",
     "Unit: Container",
     None,
     ["OTHERS-0003", "TRANSPORTATION-0001"],
     [L("Outside Carrier Management", "Container", "-", "Per container", ["OTHERS-0003", "TRANSPORTATION-0001"], None, b2b=175)]),
])

# ---------------------------------------------------------------- RETURNS
section("RETURNS", [
 svc("RT-01", "Returns Receiving", "Both",
     "Receive a returned package, perform a minor inspection, photograph the item and report back to the client; UNIS waits for disposition instructions.",
     "Per package (tracking #) plus per item; alternatives per carton / pallet / hour",
     "Unit: Package (tracking #) | Item (piece) | Carton | Pallet | Hour",
     "Inspection beyond 'minor' bills under RT-02; restocking under RT-03. D2C template: $2.50 per order + $0.75 per item.",
     [H(36), H(37), H(38), H(39), "RMS-001"],
     [L("Returns Receiving", "Package", "Unit", "Per package / tracking #", ["RMS-001"], None, d2c=2.5),
      L("Returns Receiving", "Item", "Unit", "Per item (piece)", [H(39)], None, d2c=0.75),
      L("Returns Receiving", "Carton", "Unit", "Per carton", [H(36)], None),
      L("Returns Receiving", "Pallet", "Unit", "Per pallet", [H(38)], None),
      L("Returns Receiving", "Hour", "Unit", "Per hour", [H(37)], None)]),
 svc("RT-02", "Return Inspection (grading)", "Both",
     "Inspect returned units beyond the minor check included in RT-01 and grade them for disposition.",
     "Per unit, or per hour",
     "Level: Standard inspection | Complex inspection | Hourly inspection",
     None,
     ["RMS-002", "RMS-003", "RMS-004"],
     [L("Return Inspection", "Unit", "Level", "Standard", ["RMS-002"], None),
      L("Return Inspection", "Unit", "Level", "Complex", ["RMS-003"], None),
      L("Return Inspection", "Hour", "Level", "Hourly", ["RMS-004"], None)]),
 svc("RT-03", "Restocking", "Both",
     "Return a sellable returned unit to available inventory.",
     "Per unit",
     "Unit: Each",
     None,
     ["RMS-006", H(236)],
     [L("Restocking", "Each", "-", "Per unit", ["RMS-006", H(236)], None)]),
 svc("RT-04", "Drop-Ship Re-Processing", "D2C",
     "Re-process a drop-ship order that was returned / refused and must be re-shipped.",
     "Per unit",
     "Unit: Unit",
     None,
     [H(192)],
     [L("Drop-Ship Re-Processing", "Unit", "-", "Per unit", [H(192)], None)]),
 svc("RT-05", "Disposal / Destruction", "Both",
     "Dispose of or destroy unsellable product at client request.",
     "Per unit (plus hauling cost-plus)",
     "Unit: Unit",
     None,
     [A(11)],
     [L("Disposal", "Unit", "-", "Per unit", [A(11)], None)]),
])

# ---------------------------------------------------------------- LABOR
section("LABOR & INVENTORY CONTROL", [
 svc("LB-01", "Hourly Labor (general)", "Both",
     "Any non-standard work outside the ordinary handling scope; overtime applies to client-requested after-hours work.",
     "Per labor hour, billed in 15-minute increments",
     "Rate tier: Regular | Overtime | Overnight clerk | Special project (with minimum project charge)",
     "Use the task-specific lines in LB-02 when the task is known, so the invoice explains the work.",
     [H(199), "HOURLY LABOR", H(213), H(225), H(223), H(224), A(32), A(29)],
     [L("Hourly Labor", "Hour", "Rate tier", "Regular", [H(199), "HOURLY LABOR", H(213), A(32), A(29)], None, b2b=50, d2c=50),
      L("Hourly Labor", "Hour", "Rate tier", "Overtime", [H(225), H(223)], None, b2b=75, d2c=75)]),
 svc("LB-02", "Task-Specific Labor (hourly)", "Both",
     "Hourly work for a named task, so the invoice shows what the labor was for: rework, sorting, scanning, clean-up, inbound / outbound QC, inventory consolidation, palletizing & wrapping.",
     "Per labor hour, billed in 15-minute increments",
     "Task: Rework | Sorting | Scanning | Clean-up | Inbound QC | Outbound QC | Inventory consolidation | Palletizing & wrapping",
     "Default rate = LB-01 regular rate unless quoted otherwise.",
     [H(238), H(246), H(240), "OTHERS-0002", H(201), H(221), H(204), H(227)],
     [L("Task Labor", "Hour", "Task", "Rework", [H(238)], None),
      L("Task Labor", "Hour", "Task", "Sorting", [H(246)], None),
      L("Task Labor", "Hour", "Task", "Inventory consolidation", [H(204)], None),
      L("Task Labor", "Hour", "Task", "Palletizing & wrapping", [H(227)], None)]),
 svc("LB-03", "Inventory Counts (cycle / annual)", "Both",
     "Physical count support for cycle counts or annual inventory requested by the client.",
     "Per labor hour, billed in 15-minute increments",
     "Type: Cycle count | Annual / full physical inventory",
     None,
     [A(10)],
     [L("Inventory Counts", "Hour", "Type", "Cycle count / annual inventory", [A(10)], None, b2b=50, d2c=50)]),
])

# ---------------------------------------------------------------- DOCS & ADMIN
section("DOCUMENTS & ADMINISTRATION", [
 svc("DC-01", "Shipping & Customs Documents", "Both",
     "Prepare shipping or customs paperwork on request: BOL, packing list, international documents (BOL / invoice / packing list), customs-bond documents, international manifest.",
     "Per document (international manifest per order)",
     "Document: Packing list | Bill of lading | Customized / international shipping document | Customs bond document | International manifest",
     None,
     [A(23), A(6), A(9), A(8), A(13)],
     [L("Documents", "Document", "Document", "Packing list", [A(23)], None, d2c=0.35),
      L("Documents", "Document", "Document", "Bill of lading (BOL)", [A(6)], None),
      L("Documents", "Document", "Document", "Customized / international shipping document", [A(9)], None, b2b=10, d2c=10),
      L("Documents", "Document", "Document", "Customs bond document", [A(8)], None),
      L("Documents", "Order", "Document", "International manifest", [A(13)], None, d2c=0.5)]),
 svc("DC-02", "Copies & Document Scanning", "Both",
     "Photocopies or scans of documents, only when requested.",
     "Per page / document",
     "Type: Photocopy (B&W) | Document scan",
     None,
     [A(26), A(12)],
     [L("Copies & Scanning", "Document", "Type", "Photocopy (B&W)", [A(26)], None, b2b=1, d2c=1),
      L("Copies & Scanning", "Document", "Type", "Document scan", [A(12)], None)]),
 svc("DC-03", "Account Administration Fee", "Both",
     "Recurring account-management / clerical administration fee (customer service, reporting, bonded paperwork).",
     "Per month (or per service)",
     "Type: Monthly administration | Customer service | One-off admin fee",
     "Wide spread in current use ($25 - $6,000): define scope in the SOW before quoting.",
     [A(5), A(17), H(191)],
     [L("Account Administration", "Month / service", "Type", "Admin fee", [A(5)], None)]),
])

# ---------------------------------------------------------------- IT
EDI = [H(1), H(2), H(45), H(46), H(47), H(48), H(49), H(50), H(98), H(99), H(100), H(101), H(102), H(103)]
section("IT, EDI & SYSTEMS", [
 svc("IT-01", "WMS / System Access & Maintenance", "Both",
     "Monthly WMS / IT maintenance per user, or an enterprise WISE WMS subscription for the client entity.",
     "Per user per month, or per entity subscription",
     "Plan: Per user / month | Enterprise single-entity subscription",
     "Current templates: $175 per user per month (internal note: do not list on the card).",
     ["SYSTEM & MANAGEMENT FEE-0005", "SYSTEM & MANAGEMENT FEE-0004", "SYSTEM & MANAGEMENT FEE-0003"],
     [L("WMS Access", "User / month", "Plan", "Per user per month", ["SYSTEM & MANAGEMENT FEE-0005"], r"maintenance|user"),
      L("WMS Access", "Entity", "Plan", "Enterprise single-entity subscription", ["SYSTEM & MANAGEMENT FEE-0004"], None)]),
 svc("IT-02", "Implementation & Onboarding (project)", "Both",
     "One-time onboarding: kickoff, requirements & spec gathering, customer / facility setup in WISE (WMS) and BNP (billing), EDI/FTP data mapping & development, retailer label & document setup, UAT (inbound / outbound / other), training and go-live meetings.",
     "Per project phase (quoted), or IT hourly",
     "Phase: Kickoff & requirements | Customer / facility setup (WISE, BNP) | EDI / FTP mapping & development | Retailer labels & documents setup | UAT (inbound / outbound / other) | Training | Pre / post go-live meetings",
     "Most integration setup is quoted case by case ('Quote available upon request' on templates).",
     [H(206), H(235), H(205), H(218), H(189), H(190), H(193), H(194), H(244), H(202), H(222), H(220), H(248), H(230), H(229)],
     [L("Implementation", "Project", "Phase", "EDI / FTP integration (quoted)", [H(194), H(193)], None)]),
 svc("IT-03", "Item / SKU Setup", "Both",
     "Import the client's item master into the WMS at onboarding, and set up each additional SKU afterwards.",
     "One-time fee (initial import) + per additional SKU",
     "Type: Initial item-master import (one-time) | Additional SKU setup (per SKU)",
     None,
     [H(200), A(14)],
     [L("Item Setup", "One-time", "Type", "Initial item-master import", [H(200)], None, b2b=300),
      L("Item Setup", "SKU", "Type", "Additional SKU setup", [A(14)], None, b2b=5.75)]),
 svc("IT-04", "IT Support (ongoing)", "Both",
     "IT work requested outside normal system operation (reports, changes, troubleshooting).",
     "Per IT hour / per request",
     "Unit: Hour | Request",
     "B2B template $150/hr vs D2C template $200/hr - align.",
     [H(217)],
     [L("IT Support", "Hour", "-", "Per IT hour", [H(217)], None, b2b=150, d2c=200)]),
 svc("IT-05", "EDI / FTP Transaction Fees", "Both",
     "Per-transaction charge for electronic documents exchanged with the client or its trading partners (orders, ship confirmations, ASNs, receipts) and VAN pass-through.",
     "Per document / order / receipt / load",
     "Channel: EDI (AS2 / VAN) | FTP (UNIS-hosted). Document: 940 order | 945 ship confirm | 856 ASN | 850 PO / receipt | FTP file. Unit: Order | Receipt | Load | Document. VAN charge: cost-plus",
     "Replaces manual-entry charges (OB-02 / IN-11) for electronically received documents.",
     EDI,
     [L("EDI / FTP Transaction", "Document", "Channel", "EDI document (940 / 945 / 856 / 850)", [H(102), H(103), H(99), H(48), H(49), H(50)], None, b2b=0.5),
      L("EDI / FTP Transaction", "Transaction", "Channel", "FTP transaction", [H(1), H(2), H(45), H(46), H(47)], None, b2b=0.5),
      L("EDI / FTP Transaction", "Document", "Channel", "EDI VAN charge (cost-plus)", [H(98), H(100), H(101)], None)]),
])

# ---------------------------------------------------------------- MATERIALS
section("MATERIALS & SUPPLIES", [
 svc("MAT-01", "Pallet Securing & Pallet Materials", "B2B",
     "Materials and labor to secure a pallet for shipment, and pallets supplied by UNIS.",
     "Per pallet",
     "Item: Stretch wrap | Plastic strapping | Slip sheet | Top sheet / topper | Corner boards* | Pallet Grade A* | Pallet Grade B*  (*no billing code yet)",
     "Pallets: per pallet or market rate + 20%.",
     [A(33), "OTHERS-0004", "SLIPSHEET", "OTHERS-0005"],
     [L("Pallet Materials", "Pallet", "Item", "Stretch wrap", [A(33)], None, b2b=5.7, d2c=5.7),
      L("Pallet Materials", "Pallet", "Item", "Plastic strapping", ["OTHERS-0004"], None, b2b=6.5, d2c=6.5),
      L("Pallet Materials", "Pallet", "Item", "Slip sheet", ["SLIPSHEET"], None),
      L("Pallet Materials", "Pallet", "Item", "Corner boards - NO CODE", [], None, b2b=6.5, d2c=6.5),
      L("Pallet Materials", "Pallet", "Item", "Pallet Grade A (40x48) - NO CODE", [], None, b2b=18.75, d2c=18.75),
      L("Pallet Materials", "Pallet", "Item", "Pallet Grade B (40x48) - NO CODE", [], None, b2b=14.75, d2c=14.75)]),
 svc("MAT-02", "Supplies (cost-plus)", "Both",
     "Packaging, warehouse and office supplies purchased by UNIS for the client and re-billed at cost plus a markup.",
     "Cost + markup (template: +20%)",
     "Category: Packaging materials | Warehouse supplies | Office supplies | Other material",
     "Rate is a markup %, not a unit price.",
     ["Freight-0001", A(35), A(19), A(22), A(38)],
     [L("Supplies", "Cost + %", "Category", "Any supplies", ["Freight-0001", A(35), A(19), A(22), A(38)], None, ratetype="Mark Up")]),
 svc("MAT-03", "Facility & Equipment Pass-Throughs", "B2B",
     "Client-specific facility costs re-billed: rental equipment, waste removal, utility jobs, security.",
     "Per hour / per unit / per occurrence (usually cost-plus)",
     "Item: Rental equipment | Waste removal | Utility job | Security charge",
     None,
     [A(28), A(36), A(34), H(241)],
     [L("Pass-Through", "Hour", "Item", "Utility job", [A(34)], None)]),
])

# ---------------------------------------------------------------- FINANCIAL (non-quote)
section("BILLING ADJUSTMENTS (internal - not shown on customer quote)", [
 svc("FN-01", "Claims", "Internal",
     "Credit or charge arising from a handling, storage, freight or drayage claim.",
     "Per claim", "Source: Handling | Storage | Small parcel freight | Drayage | General",
     "Not a service - excluded from the quote page.",
     [A(4), H(198), S(29), "Small Parcel-0006", "DRAYAGE-0002"], []),
 svc("FN-02", "Discounts & Incentives", "Internal",
     "Discount or incentive-program credit applied on the invoice.",
     "Per invoice", "Type: Discount | Incentive program",
     "Not a service - excluded from the quote page.",
     ["DISCOUNT-0001", "Gift-0001"], []),
 svc("FN-03", "Late Payment Fee", "Internal",
     "Late fee on overdue balance (configured at 2%).",
     "% of overdue balance", "-", "Payment term - belongs in the contract, not the rate card.",
     ["LATE CHARGE-0001"], []),
 svc("FN-04", "Security Deposit", "Internal",
     "Deposit collected before go-live.", "Flat", "-", "Contract term.",
     ["SECURITY DEPOSIT-0001"], []),
 svc("FN-05", "Miscellaneous / Generic Charges", "Internal",
     "Catch-all codes used for one-off charges that have no specific code.",
     "Varies", "-", "Review usage and re-map to a specific service where possible.",
     ["MISCELLANEOUS REVENUE-0001", A(3), H(254)], []),
])
